/**
 * ISO 3166-1 alpha-2 reference data — every country/territory in the world,
 * with international dialling code and localised names for all 15 supported
 * UI languages. Used by the country selector, the phone field and the address
 * autocompletion. No network call, no API key: fully deterministic.
 */

export interface Country {
  code: string;
  dial: string;
  names: Record<string, string>;
}

export const COUNTRIES: Country[] = [
  { code: "AD", dial: "+376", names: {"en":"Andorra","fr":"Andorre","de":"Andorra","es":"Andorra","it":"Andorra","nl":"Andorra","pl":"Andora","ro":"Andorra","el":"Ανδόρα","bg":"Андора","sk":"Andorra","sl":"Andora","fi":"Andorra","hr":"Andora","hu":"Andorra"} },
  { code: "AE", dial: "+971", names: {"en":"United Arab Emirates","fr":"Émirats arabes unis","de":"Vereinigte Arabische Emirate","es":"Emiratos Árabes Unidos","it":"Emirati Arabi Uniti","nl":"Verenigde Arabische Emiraten","pl":"Zjednoczone Emiraty Arabskie","ro":"Emiratele Arabe Unite","el":"Ηνωμένα Αραβικά Εμιράτα","bg":"Обединени арабски емирства","sk":"Spojené arabské emiráty","sl":"Združeni arabski emirati","fi":"Arabiemiirikunnat","hr":"Ujedinjeni Arapski Emirati","hu":"Egyesült Arab Emírségek"} },
  { code: "AF", dial: "+93", names: {"en":"Afghanistan","fr":"Afghanistan","de":"Afghanistan","es":"Afganistán","it":"Afghanistan","nl":"Afghanistan","pl":"Afganistan","ro":"Afganistan","el":"Αφγανιστάν","bg":"Афганистан","sk":"Afganistan","sl":"Afganistan","fi":"Afganistan","hr":"Afganistan","hu":"Afganisztán"} },
  { code: "AG", dial: "+1268", names: {"en":"Antigua & Barbuda","fr":"Antigua-et-Barbuda","de":"Antigua und Barbuda","es":"Antigua y Barbuda","it":"Antigua e Barbuda","nl":"Antigua en Barbuda","pl":"Antigua i Barbuda","ro":"Antigua și Barbuda","el":"Αντίγκουα και Μπαρμπούντα","bg":"Антигуа и Барбуда","sk":"Antigua a Barbuda","sl":"Antigva in Barbuda","fi":"Antigua ja Barbuda","hr":"Antigva i Barbuda","hu":"Antigua és Barbuda"} },
  { code: "AI", dial: "+1264", names: {"en":"Anguilla","fr":"Anguilla","de":"Anguilla","es":"Anguila","it":"Anguilla","nl":"Anguilla","pl":"Anguilla","ro":"Anguilla","el":"Ανγκουίλα","bg":"Ангуила","sk":"Anguilla","sl":"Angvila","fi":"Anguilla","hr":"Angvila","hu":"Anguilla"} },
  { code: "AL", dial: "+355", names: {"en":"Albania","fr":"Albanie","de":"Albanien","es":"Albania","it":"Albania","nl":"Albanië","pl":"Albania","ro":"Albania","el":"Αλβανία","bg":"Албания","sk":"Albánsko","sl":"Albanija","fi":"Albania","hr":"Albanija","hu":"Albánia"} },
  { code: "AM", dial: "+374", names: {"en":"Armenia","fr":"Arménie","de":"Armenien","es":"Armenia","it":"Armenia","nl":"Armenië","pl":"Armenia","ro":"Armenia","el":"Αρμενία","bg":"Армения","sk":"Arménsko","sl":"Armenija","fi":"Armenia","hr":"Armenija","hu":"Örményország"} },
  { code: "AO", dial: "+244", names: {"en":"Angola","fr":"Angola","de":"Angola","es":"Angola","it":"Angola","nl":"Angola","pl":"Angola","ro":"Angola","el":"Αγκόλα","bg":"Ангола","sk":"Angola","sl":"Angola","fi":"Angola","hr":"Angola","hu":"Angola"} },
  { code: "AQ", dial: "+672", names: {"en":"Antarctica","fr":"Antarctique","de":"Antarktis","es":"Antártida","it":"Antartide","nl":"Antarctica","pl":"Antarktyda","ro":"Antarctica","el":"Ανταρκτική","bg":"Антарктика","sk":"Antarktída","sl":"Antarktika","fi":"Antarktis","hr":"Antarktika","hu":"Antarktisz"} },
  { code: "AR", dial: "+54", names: {"en":"Argentina","fr":"Argentine","de":"Argentinien","es":"Argentina","it":"Argentina","nl":"Argentinië","pl":"Argentyna","ro":"Argentina","el":"Αργεντινή","bg":"Аржентина","sk":"Argentína","sl":"Argentina","fi":"Argentiina","hr":"Argentina","hu":"Argentína"} },
  { code: "AS", dial: "+1684", names: {"en":"American Samoa","fr":"Samoa américaines","de":"Amerikanisch-Samoa","es":"Samoa Americana","it":"Samoa Americane","nl":"Amerikaans-Samoa","pl":"Samoa Amerykańskie","ro":"Samoa Americană","el":"Αμερικανική Σαμόα","bg":"Американска Самоа","sk":"Americká Samoa","sl":"Ameriška Samoa","fi":"Amerikan Samoa","hr":"Američka Samoa","hu":"Amerikai Szamoa"} },
  { code: "AT", dial: "+43", names: {"en":"Austria","fr":"Autriche","de":"Österreich","es":"Austria","it":"Austria","nl":"Oostenrijk","pl":"Austria","ro":"Austria","el":"Αυστρία","bg":"Австрия","sk":"Rakúsko","sl":"Avstrija","fi":"Itävalta","hr":"Austrija","hu":"Ausztria"} },
  { code: "AU", dial: "+61", names: {"en":"Australia","fr":"Australie","de":"Australien","es":"Australia","it":"Australia","nl":"Australië","pl":"Australia","ro":"Australia","el":"Αυστραλία","bg":"Австралия","sk":"Austrália","sl":"Avstralija","fi":"Australia","hr":"Australija","hu":"Ausztrália"} },
  { code: "AW", dial: "+297", names: {"en":"Aruba","fr":"Aruba","de":"Aruba","es":"Aruba","it":"Aruba","nl":"Aruba","pl":"Aruba","ro":"Aruba","el":"Αρούμπα","bg":"Аруба","sk":"Aruba","sl":"Aruba","fi":"Aruba","hr":"Aruba","hu":"Aruba"} },
  { code: "AX", dial: "+358", names: {"en":"Åland Islands","fr":"Îles Åland","de":"Ålandinseln","es":"Islas Aland","it":"Isole Åland","nl":"Åland","pl":"Wyspy Alandzkie","ro":"Insulele Åland","el":"Νήσοι Όλαντ","bg":"Оландски острови","sk":"Alandy","sl":"Ålandski otoki","fi":"Ahvenanmaa","hr":"Ålandski otoci","hu":"Åland-szigetek"} },
  { code: "AZ", dial: "+994", names: {"en":"Azerbaijan","fr":"Azerbaïdjan","de":"Aserbaidschan","es":"Azerbaiyán","it":"Azerbaigian","nl":"Azerbeidzjan","pl":"Azerbejdżan","ro":"Azerbaidjan","el":"Αζερμπαϊτζάν","bg":"Азербайджан","sk":"Azerbajdžan","sl":"Azerbajdžan","fi":"Azerbaidžan","hr":"Azerbajdžan","hu":"Azerbajdzsán"} },
  { code: "BA", dial: "+387", names: {"en":"Bosnia & Herzegovina","fr":"Bosnie-Herzégovine","de":"Bosnien und Herzegowina","es":"Bosnia y Herzegovina","it":"Bosnia ed Erzegovina","nl":"Bosnië en Herzegovina","pl":"Bośnia i Hercegowina","ro":"Bosnia și Herțegovina","el":"Βοσνία - Ερζεγοβίνη","bg":"Босна и Херцеговина","sk":"Bosna a Hercegovina","sl":"Bosna in Hercegovina","fi":"Bosnia ja Hertsegovina","hr":"Bosna i Hercegovina","hu":"Bosznia-Hercegovina"} },
  { code: "BB", dial: "+1246", names: {"en":"Barbados","fr":"Barbade","de":"Barbados","es":"Barbados","it":"Barbados","nl":"Barbados","pl":"Barbados","ro":"Barbados","el":"Μπαρμπέιντος","bg":"Барбадос","sk":"Barbados","sl":"Barbados","fi":"Barbados","hr":"Barbados","hu":"Barbados"} },
  { code: "BD", dial: "+880", names: {"en":"Bangladesh","fr":"Bangladesh","de":"Bangladesch","es":"Bangladés","it":"Bangladesh","nl":"Bangladesh","pl":"Bangladesz","ro":"Bangladesh","el":"Μπανγκλαντές","bg":"Бангладеш","sk":"Bangladéš","sl":"Bangladeš","fi":"Bangladesh","hr":"Bangladeš","hu":"Banglades"} },
  { code: "BE", dial: "+32", names: {"en":"Belgium","fr":"Belgique","de":"Belgien","es":"Bélgica","it":"Belgio","nl":"België","pl":"Belgia","ro":"Belgia","el":"Βέλγιο","bg":"Белгия","sk":"Belgicko","sl":"Belgija","fi":"Belgia","hr":"Belgija","hu":"Belgium"} },
  { code: "BF", dial: "+226", names: {"en":"Burkina Faso","fr":"Burkina Faso","de":"Burkina Faso","es":"Burkina Faso","it":"Burkina Faso","nl":"Burkina Faso","pl":"Burkina Faso","ro":"Burkina Faso","el":"Μπουρκίνα Φάσο","bg":"Буркина Фасо","sk":"Burkina Faso","sl":"Burkina Faso","fi":"Burkina Faso","hr":"Burkina Faso","hu":"Burkina Faso"} },
  { code: "BG", dial: "+359", names: {"en":"Bulgaria","fr":"Bulgarie","de":"Bulgarien","es":"Bulgaria","it":"Bulgaria","nl":"Bulgarije","pl":"Bułgaria","ro":"Bulgaria","el":"Βουλγαρία","bg":"България","sk":"Bulharsko","sl":"Bolgarija","fi":"Bulgaria","hr":"Bugarska","hu":"Bulgária"} },
  { code: "BH", dial: "+973", names: {"en":"Bahrain","fr":"Bahreïn","de":"Bahrain","es":"Baréin","it":"Bahrein","nl":"Bahrein","pl":"Bahrajn","ro":"Bahrain","el":"Μπαχρέιν","bg":"Бахрейн","sk":"Bahrajn","sl":"Bahrajn","fi":"Bahrain","hr":"Bahrein","hu":"Bahrein"} },
  { code: "BI", dial: "+257", names: {"en":"Burundi","fr":"Burundi","de":"Burundi","es":"Burundi","it":"Burundi","nl":"Burundi","pl":"Burundi","ro":"Burundi","el":"Μπουρούντι","bg":"Бурунди","sk":"Burundi","sl":"Burundi","fi":"Burundi","hr":"Burundi","hu":"Burundi"} },
  { code: "BJ", dial: "+229", names: {"en":"Benin","fr":"Bénin","de":"Benin","es":"Benín","it":"Benin","nl":"Benin","pl":"Benin","ro":"Benin","el":"Μπενίν","bg":"Бенин","sk":"Benin","sl":"Benin","fi":"Benin","hr":"Benin","hu":"Benin"} },
  { code: "BL", dial: "+590", names: {"en":"St. Barthélemy","fr":"Saint-Barthélemy","de":"St. Barthélemy","es":"San Bartolomé","it":"Saint-Barthélemy","nl":"Saint-Barthélemy","pl":"Saint-Barthélemy","ro":"Saint-Barthélemy","el":"Άγιος Βαρθολομαίος","bg":"Сен Бартелеми","sk":"Svätý Bartolomej","sl":"Saint Barthélemy","fi":"Saint-Barthélemy","hr":"Saint Barthélemy","hu":"Saint-Barthélemy"} },
  { code: "BM", dial: "+1441", names: {"en":"Bermuda","fr":"Bermudes","de":"Bermuda","es":"Bermudas","it":"Bermuda","nl":"Bermuda","pl":"Bermudy","ro":"Bermuda","el":"Βερμούδες","bg":"Бермудски острови","sk":"Bermudy","sl":"Bermudi","fi":"Bermuda","hr":"Bermudi","hu":"Bermuda"} },
  { code: "BN", dial: "+673", names: {"en":"Brunei","fr":"Brunei","de":"Brunei Darussalam","es":"Brunéi","it":"Brunei","nl":"Brunei","pl":"Brunei","ro":"Brunei","el":"Μπρουνέι","bg":"Бруней Даруссалам","sk":"Brunej","sl":"Brunej","fi":"Brunei","hr":"Brunej","hu":"Brunei"} },
  { code: "BO", dial: "+591", names: {"en":"Bolivia","fr":"Bolivie","de":"Bolivien","es":"Bolivia","it":"Bolivia","nl":"Bolivia","pl":"Boliwia","ro":"Bolivia","el":"Βολιβία","bg":"Боливия","sk":"Bolívia","sl":"Bolivija","fi":"Bolivia","hr":"Bolivija","hu":"Bolívia"} },
  { code: "BQ", dial: "+599", names: {"en":"Caribbean Netherlands","fr":"Pays-Bas caribéens","de":"Karibische Niederlande","es":"Caribe neerlandés","it":"Caraibi Olandesi","nl":"Caribisch Nederland","pl":"Niderlandy Karaibskie","ro":"Insulele Caraibe Olandeze","el":"Ολλανδία Καραϊβικής","bg":"Карибска Нидерландия","sk":"Karibské Holandsko","sl":"Nizozemski Karibi","fi":"Karibian Alankomaat","hr":"Karipski otoci Nizozemske","hu":"Holland Karib-térség"} },
  { code: "BR", dial: "+55", names: {"en":"Brazil","fr":"Brésil","de":"Brasilien","es":"Brasil","it":"Brasile","nl":"Brazilië","pl":"Brazylia","ro":"Brazilia","el":"Βραζιλία","bg":"Бразилия","sk":"Brazília","sl":"Brazilija","fi":"Brasilia","hr":"Brazil","hu":"Brazília"} },
  { code: "BS", dial: "+1242", names: {"en":"Bahamas","fr":"Bahamas","de":"Bahamas","es":"Bahamas","it":"Bahamas","nl":"Bahama’s","pl":"Bahamy","ro":"Bahamas","el":"Μπαχάμες","bg":"Бахамски острови","sk":"Bahamy","sl":"Bahami","fi":"Bahama","hr":"Bahami","hu":"Bahama-szigetek"} },
  { code: "BT", dial: "+975", names: {"en":"Bhutan","fr":"Bhoutan","de":"Bhutan","es":"Bután","it":"Bhutan","nl":"Bhutan","pl":"Bhutan","ro":"Bhutan","el":"Μπουτάν","bg":"Бутан","sk":"Bhután","sl":"Butan","fi":"Bhutan","hr":"Butan","hu":"Bhután"} },
  { code: "BW", dial: "+267", names: {"en":"Botswana","fr":"Botswana","de":"Botsuana","es":"Botsuana","it":"Botswana","nl":"Botswana","pl":"Botswana","ro":"Botswana","el":"Μποτσουάνα","bg":"Ботсвана","sk":"Botswana","sl":"Bocvana","fi":"Botswana","hr":"Bocvana","hu":"Botswana"} },
  { code: "BY", dial: "+375", names: {"en":"Belarus","fr":"Biélorussie","de":"Belarus","es":"Bielorrusia","it":"Bielorussia","nl":"Belarus","pl":"Białoruś","ro":"Belarus","el":"Λευκορωσία","bg":"Беларус","sk":"Bielorusko","sl":"Belorusija","fi":"Valko-Venäjä","hr":"Bjelorusija","hu":"Belarusz"} },
  { code: "BZ", dial: "+501", names: {"en":"Belize","fr":"Belize","de":"Belize","es":"Belice","it":"Belize","nl":"Belize","pl":"Belize","ro":"Belize","el":"Μπελίζ","bg":"Белиз","sk":"Belize","sl":"Belize","fi":"Belize","hr":"Belize","hu":"Belize"} },
  { code: "CA", dial: "+1", names: {"en":"Canada","fr":"Canada","de":"Kanada","es":"Canadá","it":"Canada","nl":"Canada","pl":"Kanada","ro":"Canada","el":"Καναδάς","bg":"Канада","sk":"Kanada","sl":"Kanada","fi":"Kanada","hr":"Kanada","hu":"Kanada"} },
  { code: "CC", dial: "+61", names: {"en":"Cocos (Keeling) Islands","fr":"Îles Cocos","de":"Kokosinseln","es":"Islas Cocos","it":"Isole Cocos (Keeling)","nl":"Cocoseilanden","pl":"Wyspy Kokosowe","ro":"Insulele Cocos (Keeling)","el":"Νήσοι Κόκος (Κίλινγκ)","bg":"Кокосови острови (острови Кийлинг)","sk":"Kokosové ostrovy","sl":"Kokosovi otoki","fi":"Kookossaaret (Keelingsaaret)","hr":"Kokosovi (Keelingovi) Otoci","hu":"Kókusz (Keeling)-szigetek"} },
  { code: "CD", dial: "+243", names: {"en":"Congo - Kinshasa","fr":"Congo-Kinshasa","de":"Kongo-Kinshasa","es":"República Democrática del Congo","it":"Congo - Kinshasa","nl":"Congo-Kinshasa","pl":"Demokratyczna Republika Konga","ro":"Congo - Kinshasa","el":"Κονγκό - Κινσάσα","bg":"Конго (Киншаса)","sk":"Konžská demokratická republika","sl":"Demokratična republika Kongo","fi":"Kongon demokraattinen tasavalta","hr":"Kongo - Kinshasa","hu":"Kongó – Kinshasa"} },
  { code: "CF", dial: "+236", names: {"en":"Central African Republic","fr":"République centrafricaine","de":"Zentralafrikanische Republik","es":"República Centroafricana","it":"Repubblica Centrafricana","nl":"Centraal-Afrikaanse Republiek","pl":"Republika Środkowoafrykańska","ro":"Republica Centrafricană","el":"Κεντροαφρικανική Δημοκρατία","bg":"Централноафриканска република","sk":"Stredoafrická republika","sl":"Srednjeafriška republika","fi":"Keski-Afrikan tasavalta","hr":"Srednjoafrička Republika","hu":"Közép-afrikai Köztársaság"} },
  { code: "CG", dial: "+242", names: {"en":"Congo - Brazzaville","fr":"Congo-Brazzaville","de":"Kongo-Brazzaville","es":"Congo","it":"Congo-Brazzaville","nl":"Congo-Brazzaville","pl":"Kongo","ro":"Congo - Brazzaville","el":"Κονγκό - Μπραζαβίλ","bg":"Конго (Бразавил)","sk":"Konžská republika","sl":"Kongo - Brazzaville","fi":"Kongon tasavalta","hr":"Kongo - Brazzaville","hu":"Kongó – Brazzaville"} },
  { code: "CH", dial: "+41", names: {"en":"Switzerland","fr":"Suisse","de":"Schweiz","es":"Suiza","it":"Svizzera","nl":"Zwitserland","pl":"Szwajcaria","ro":"Elveția","el":"Ελβετία","bg":"Швейцария","sk":"Švajčiarsko","sl":"Švica","fi":"Sveitsi","hr":"Švicarska","hu":"Svájc"} },
  { code: "CI", dial: "+225", names: {"en":"Côte d’Ivoire","fr":"Côte d’Ivoire","de":"Côte d’Ivoire","es":"Côte d’Ivoire","it":"Costa d’Avorio","nl":"Ivoorkust","pl":"Côte d’Ivoire","ro":"Côte d’Ivoire","el":"Ακτή Ελεφαντοστού","bg":"Кот д’Ивоар","sk":"Pobrežie Slonoviny","sl":"Slonokoščena obala","fi":"Norsunluurannikko","hr":"Obala Bjelokosti","hu":"Elefántcsontpart"} },
  { code: "CK", dial: "+682", names: {"en":"Cook Islands","fr":"Îles Cook","de":"Cookinseln","es":"Islas Cook","it":"Isole Cook","nl":"Cookeilanden","pl":"Wyspy Cooka","ro":"Insulele Cook","el":"Νήσοι Κουκ","bg":"острови Кук","sk":"Cookove ostrovy","sl":"Cookovi otoki","fi":"Cookinsaaret","hr":"Cookovi Otoci","hu":"Cook-szigetek"} },
  { code: "CL", dial: "+56", names: {"en":"Chile","fr":"Chili","de":"Chile","es":"Chile","it":"Cile","nl":"Chili","pl":"Chile","ro":"Chile","el":"Χιλή","bg":"Чили","sk":"Čile","sl":"Čile","fi":"Chile","hr":"Čile","hu":"Chile"} },
  { code: "CM", dial: "+237", names: {"en":"Cameroon","fr":"Cameroun","de":"Kamerun","es":"Camerún","it":"Camerun","nl":"Kameroen","pl":"Kamerun","ro":"Camerun","el":"Καμερούν","bg":"Камерун","sk":"Kamerun","sl":"Kamerun","fi":"Kamerun","hr":"Kamerun","hu":"Kamerun"} },
  { code: "CN", dial: "+86", names: {"en":"China","fr":"Chine","de":"China","es":"China","it":"Cina","nl":"China","pl":"Chiny","ro":"China","el":"Κίνα","bg":"Китай","sk":"Čína","sl":"Kitajska","fi":"Kiina","hr":"Kina","hu":"Kína"} },
  { code: "CO", dial: "+57", names: {"en":"Colombia","fr":"Colombie","de":"Kolumbien","es":"Colombia","it":"Colombia","nl":"Colombia","pl":"Kolumbia","ro":"Columbia","el":"Κολομβία","bg":"Колумбия","sk":"Kolumbia","sl":"Kolumbija","fi":"Kolumbia","hr":"Kolumbija","hu":"Kolumbia"} },
  { code: "CR", dial: "+506", names: {"en":"Costa Rica","fr":"Costa Rica","de":"Costa Rica","es":"Costa Rica","it":"Costa Rica","nl":"Costa Rica","pl":"Kostaryka","ro":"Costa Rica","el":"Κόστα Ρίκα","bg":"Коста Рика","sk":"Kostarika","sl":"Kostarika","fi":"Costa Rica","hr":"Kostarika","hu":"Costa Rica"} },
  { code: "CU", dial: "+53", names: {"en":"Cuba","fr":"Cuba","de":"Kuba","es":"Cuba","it":"Cuba","nl":"Cuba","pl":"Kuba","ro":"Cuba","el":"Κούβα","bg":"Куба","sk":"Kuba","sl":"Kuba","fi":"Kuuba","hr":"Kuba","hu":"Kuba"} },
  { code: "CV", dial: "+238", names: {"en":"Cape Verde","fr":"Cap-Vert","de":"Cabo Verde","es":"Cabo Verde","it":"Capo Verde","nl":"Kaapverdië","pl":"Republika Zielonego Przylądka","ro":"Capul Verde","el":"Πράσινο Ακρωτήριο","bg":"Кабо Верде","sk":"Kapverdy","sl":"Zelenortski otoki","fi":"Kap Verde","hr":"Zelenortska Republika","hu":"Zöld-foki Köztársaság"} },
  { code: "CW", dial: "+599", names: {"en":"Curaçao","fr":"Curaçao","de":"Curaçao","es":"Curazao","it":"Curaçao","nl":"Curaçao","pl":"Curaçao","ro":"Curaçao","el":"Κουρασάο","bg":"Кюрасао","sk":"Curaçao","sl":"Curaçao","fi":"Curaçao","hr":"Curaçao","hu":"Curaçao"} },
  { code: "CX", dial: "+61", names: {"en":"Christmas Island","fr":"Île Christmas","de":"Weihnachtsinsel","es":"Isla de Navidad","it":"Isola Christmas","nl":"Christmaseiland","pl":"Wyspa Bożego Narodzenia","ro":"Insula Christmas","el":"Νήσος των Χριστουγέννων","bg":"остров Рождество","sk":"Vianočný ostrov","sl":"Božični otok","fi":"Joulusaari","hr":"Božićni Otok","hu":"Karácsony-sziget"} },
  { code: "CY", dial: "+357", names: {"en":"Cyprus","fr":"Chypre","de":"Zypern","es":"Chipre","it":"Cipro","nl":"Cyprus","pl":"Cypr","ro":"Cipru","el":"Κύπρος","bg":"Кипър","sk":"Cyprus","sl":"Ciper","fi":"Kypros","hr":"Cipar","hu":"Ciprus"} },
  { code: "CZ", dial: "+420", names: {"en":"Czechia","fr":"Tchéquie","de":"Tschechien","es":"Chequia","it":"Cechia","nl":"Tsjechië","pl":"Czechy","ro":"Cehia","el":"Τσεχία","bg":"Чехия","sk":"Česko","sl":"Češka","fi":"Tšekki","hr":"Češka","hu":"Csehország"} },
  { code: "DE", dial: "+49", names: {"en":"Germany","fr":"Allemagne","de":"Deutschland","es":"Alemania","it":"Germania","nl":"Duitsland","pl":"Niemcy","ro":"Germania","el":"Γερμανία","bg":"Германия","sk":"Nemecko","sl":"Nemčija","fi":"Saksa","hr":"Njemačka","hu":"Németország"} },
  { code: "DJ", dial: "+253", names: {"en":"Djibouti","fr":"Djibouti","de":"Dschibuti","es":"Yibuti","it":"Gibuti","nl":"Djibouti","pl":"Dżibuti","ro":"Djibouti","el":"Τζιμπουτί","bg":"Джибути","sk":"Džibutsko","sl":"Džibuti","fi":"Djibouti","hr":"Džibuti","hu":"Dzsibuti"} },
  { code: "DK", dial: "+45", names: {"en":"Denmark","fr":"Danemark","de":"Dänemark","es":"Dinamarca","it":"Danimarca","nl":"Denemarken","pl":"Dania","ro":"Danemarca","el":"Δανία","bg":"Дания","sk":"Dánsko","sl":"Danska","fi":"Tanska","hr":"Danska","hu":"Dánia"} },
  { code: "DM", dial: "+1767", names: {"en":"Dominica","fr":"Dominique","de":"Dominica","es":"Dominica","it":"Dominica","nl":"Dominica","pl":"Dominika","ro":"Dominica","el":"Ντομίνικα","bg":"Доминика","sk":"Dominika","sl":"Dominika","fi":"Dominica","hr":"Dominika","hu":"Dominika"} },
  { code: "DO", dial: "+1809", names: {"en":"Dominican Republic","fr":"République dominicaine","de":"Dominikanische Republik","es":"República Dominicana","it":"Repubblica Dominicana","nl":"Dominicaanse Republiek","pl":"Dominikana","ro":"Republica Dominicană","el":"Δομινικανή Δημοκρατία","bg":"Доминиканска република","sk":"Dominikánska republika","sl":"Dominikanska republika","fi":"Dominikaaninen tasavalta","hr":"Dominikanska Republika","hu":"Dominikai Köztársaság"} },
  { code: "DZ", dial: "+213", names: {"en":"Algeria","fr":"Algérie","de":"Algerien","es":"Argelia","it":"Algeria","nl":"Algerije","pl":"Algieria","ro":"Algeria","el":"Αλγερία","bg":"Алжир","sk":"Alžírsko","sl":"Alžirija","fi":"Algeria","hr":"Alžir","hu":"Algéria"} },
  { code: "EC", dial: "+593", names: {"en":"Ecuador","fr":"Équateur","de":"Ecuador","es":"Ecuador","it":"Ecuador","nl":"Ecuador","pl":"Ekwador","ro":"Ecuador","el":"Ισημερινός","bg":"Еквадор","sk":"Ekvádor","sl":"Ekvador","fi":"Ecuador","hr":"Ekvador","hu":"Ecuador"} },
  { code: "EE", dial: "+372", names: {"en":"Estonia","fr":"Estonie","de":"Estland","es":"Estonia","it":"Estonia","nl":"Estland","pl":"Estonia","ro":"Estonia","el":"Εσθονία","bg":"Естония","sk":"Estónsko","sl":"Estonija","fi":"Viro","hr":"Estonija","hu":"Észtország"} },
  { code: "EG", dial: "+20", names: {"en":"Egypt","fr":"Égypte","de":"Ägypten","es":"Egipto","it":"Egitto","nl":"Egypte","pl":"Egipt","ro":"Egipt","el":"Αίγυπτος","bg":"Египет","sk":"Egypt","sl":"Egipt","fi":"Egypti","hr":"Egipat","hu":"Egyiptom"} },
  { code: "EH", dial: "+212", names: {"en":"Western Sahara","fr":"Sahara occidental","de":"Westsahara","es":"Sáhara Occidental","it":"Sahara Occidentale","nl":"Westelijke Sahara","pl":"Sahara Zachodnia","ro":"Sahara Occidentală","el":"Δυτική Σαχάρα","bg":"Западна Сахара","sk":"Západná Sahara","sl":"Zahodna Sahara","fi":"Länsi-Sahara","hr":"Zapadna Sahara","hu":"Nyugat-Szahara"} },
  { code: "ER", dial: "+291", names: {"en":"Eritrea","fr":"Érythrée","de":"Eritrea","es":"Eritrea","it":"Eritrea","nl":"Eritrea","pl":"Erytrea","ro":"Eritreea","el":"Ερυθραία","bg":"Еритрея","sk":"Eritrea","sl":"Eritreja","fi":"Eritrea","hr":"Eritreja","hu":"Eritrea"} },
  { code: "ES", dial: "+34", names: {"en":"Spain","fr":"Espagne","de":"Spanien","es":"España","it":"Spagna","nl":"Spanje","pl":"Hiszpania","ro":"Spania","el":"Ισπανία","bg":"Испания","sk":"Španielsko","sl":"Španija","fi":"Espanja","hr":"Španjolska","hu":"Spanyolország"} },
  { code: "ET", dial: "+251", names: {"en":"Ethiopia","fr":"Éthiopie","de":"Äthiopien","es":"Etiopía","it":"Etiopia","nl":"Ethiopië","pl":"Etiopia","ro":"Etiopia","el":"Αιθιοπία","bg":"Етиопия","sk":"Etiópia","sl":"Etiopija","fi":"Etiopia","hr":"Etiopija","hu":"Etiópia"} },
  { code: "FI", dial: "+358", names: {"en":"Finland","fr":"Finlande","de":"Finnland","es":"Finlandia","it":"Finlandia","nl":"Finland","pl":"Finlandia","ro":"Finlanda","el":"Φινλανδία","bg":"Финландия","sk":"Fínsko","sl":"Finska","fi":"Suomi","hr":"Finska","hu":"Finnország"} },
  { code: "FJ", dial: "+679", names: {"en":"Fiji","fr":"Fidji","de":"Fidschi","es":"Fiyi","it":"Figi","nl":"Fiji","pl":"Fidżi","ro":"Fiji","el":"Φίτζι","bg":"Фиджи","sk":"Fidži","sl":"Fidži","fi":"Fidži","hr":"Fidži","hu":"Fidzsi"} },
  { code: "FK", dial: "+500", names: {"en":"Falkland Islands","fr":"Îles Malouines","de":"Falklandinseln","es":"Islas Malvinas","it":"Isole Falkland","nl":"Falklandeilanden","pl":"Falklandy","ro":"Insulele Falkland","el":"Νήσοι Φόκλαντ","bg":"Фолкландски острови","sk":"Falklandy","sl":"Falklandski otoki","fi":"Falklandinsaaret","hr":"Falklandski Otoci","hu":"Falkland-szigetek"} },
  { code: "FM", dial: "+691", names: {"en":"Micronesia","fr":"Micronésie","de":"Mikronesien","es":"Micronesia","it":"Micronesia","nl":"Micronesia","pl":"Mikronezja","ro":"Micronezia","el":"Μικρονησία","bg":"Микронезия","sk":"Mikronézia","sl":"Mikronezija","fi":"Mikronesia","hr":"Mikronezija","hu":"Mikronézia"} },
  { code: "FO", dial: "+298", names: {"en":"Faroe Islands","fr":"Îles Féroé","de":"Färöer","es":"Islas Feroe","it":"Isole Fær Øer","nl":"Faeröer","pl":"Wyspy Owcze","ro":"Insulele Feroe","el":"Νήσοι Φερόες","bg":"Фарьорски острови","sk":"Faerské ostrovy","sl":"Ferski otoki","fi":"Färsaaret","hr":"Ovčji Otoci","hu":"Feröer szigetek"} },
  { code: "FR", dial: "+33", names: {"en":"France","fr":"France","de":"Frankreich","es":"Francia","it":"Francia","nl":"Frankrijk","pl":"Francja","ro":"Franța","el":"Γαλλία","bg":"Франция","sk":"Francúzsko","sl":"Francija","fi":"Ranska","hr":"Francuska","hu":"Franciaország"} },
  { code: "GA", dial: "+241", names: {"en":"Gabon","fr":"Gabon","de":"Gabun","es":"Gabón","it":"Gabon","nl":"Gabon","pl":"Gabon","ro":"Gabon","el":"Γκαμπόν","bg":"Габон","sk":"Gabon","sl":"Gabon","fi":"Gabon","hr":"Gabon","hu":"Gabon"} },
  { code: "GB", dial: "+44", names: {"en":"United Kingdom","fr":"Royaume-Uni","de":"Vereinigtes Königreich","es":"Reino Unido","it":"Regno Unito","nl":"Verenigd Koninkrijk","pl":"Wielka Brytania","ro":"Regatul Unit","el":"Ηνωμένο Βασίλειο","bg":"Обединеното кралство","sk":"Spojené kráľovstvo","sl":"Združeno kraljestvo","fi":"Iso-Britannia","hr":"Ujedinjeno Kraljevstvo","hu":"Egyesült Királyság"} },
  { code: "GD", dial: "+1473", names: {"en":"Grenada","fr":"Grenade","de":"Grenada","es":"Granada","it":"Grenada","nl":"Grenada","pl":"Grenada","ro":"Grenada","el":"Γρενάδα","bg":"Гренада","sk":"Grenada","sl":"Grenada","fi":"Grenada","hr":"Grenada","hu":"Grenada"} },
  { code: "GE", dial: "+995", names: {"en":"Georgia","fr":"Géorgie","de":"Georgien","es":"Georgia","it":"Georgia","nl":"Georgië","pl":"Gruzja","ro":"Georgia","el":"Γεωργία","bg":"Грузия","sk":"Gruzínsko","sl":"Gruzija","fi":"Georgia","hr":"Gruzija","hu":"Grúzia"} },
  { code: "GF", dial: "+594", names: {"en":"French Guiana","fr":"Guyane française","de":"Französisch-Guayana","es":"Guayana Francesa","it":"Guyana Francese","nl":"Frans-Guyana","pl":"Gujana Francuska","ro":"Guyana Franceză","el":"Γαλλική Γουιάνα","bg":"Френска Гвиана","sk":"Francúzska Guyana","sl":"Francoska Gvajana","fi":"Ranskan Guayana","hr":"Francuska Gijana","hu":"Francia Guyana"} },
  { code: "GG", dial: "+44", names: {"en":"Guernsey","fr":"Guernesey","de":"Guernsey","es":"Guernesey","it":"Guernsey","nl":"Guernsey","pl":"Guernsey","ro":"Guernsey","el":"Γκέρνζι","bg":"Гърнзи","sk":"Guernsey","sl":"Guernsey","fi":"Guernsey","hr":"Guernsey","hu":"Guernsey"} },
  { code: "GH", dial: "+233", names: {"en":"Ghana","fr":"Ghana","de":"Ghana","es":"Ghana","it":"Ghana","nl":"Ghana","pl":"Ghana","ro":"Ghana","el":"Γκάνα","bg":"Гана","sk":"Ghana","sl":"Gana","fi":"Ghana","hr":"Gana","hu":"Ghána"} },
  { code: "GI", dial: "+350", names: {"en":"Gibraltar","fr":"Gibraltar","de":"Gibraltar","es":"Gibraltar","it":"Gibilterra","nl":"Gibraltar","pl":"Gibraltar","ro":"Gibraltar","el":"Γιβραλτάρ","bg":"Гибралтар","sk":"Gibraltár","sl":"Gibraltar","fi":"Gibraltar","hr":"Gibraltar","hu":"Gibraltár"} },
  { code: "GL", dial: "+299", names: {"en":"Greenland","fr":"Groenland","de":"Grönland","es":"Groenlandia","it":"Groenlandia","nl":"Groenland","pl":"Grenlandia","ro":"Groenlanda","el":"Γροιλανδία","bg":"Гренландия","sk":"Grónsko","sl":"Grenlandija","fi":"Grönlanti","hr":"Grenland","hu":"Grönland"} },
  { code: "GM", dial: "+220", names: {"en":"Gambia","fr":"Gambie","de":"Gambia","es":"Gambia","it":"Gambia","nl":"Gambia","pl":"Gambia","ro":"Gambia","el":"Γκάμπια","bg":"Гамбия","sk":"Gambia","sl":"Gambija","fi":"Gambia","hr":"Gambija","hu":"Gambia"} },
  { code: "GN", dial: "+224", names: {"en":"Guinea","fr":"Guinée","de":"Guinea","es":"Guinea","it":"Guinea","nl":"Guinee","pl":"Gwinea","ro":"Guineea","el":"Γουινέα","bg":"Гвинея","sk":"Guinea","sl":"Gvineja","fi":"Guinea","hr":"Gvineja","hu":"Guinea"} },
  { code: "GP", dial: "+590", names: {"en":"Guadeloupe","fr":"Guadeloupe","de":"Guadeloupe","es":"Guadalupe","it":"Guadalupa","nl":"Guadeloupe","pl":"Gwadelupa","ro":"Guadelupa","el":"Γουαδελούπη","bg":"Гваделупа","sk":"Guadeloupe","sl":"Guadeloupe","fi":"Guadeloupe","hr":"Guadalupe","hu":"Guadeloupe"} },
  { code: "GQ", dial: "+240", names: {"en":"Equatorial Guinea","fr":"Guinée équatoriale","de":"Äquatorialguinea","es":"Guinea Ecuatorial","it":"Guinea Equatoriale","nl":"Equatoriaal-Guinea","pl":"Gwinea Równikowa","ro":"Guineea Ecuatorială","el":"Ισημερινή Γουινέα","bg":"Екваториална Гвинея","sk":"Rovníková Guinea","sl":"Ekvatorialna Gvineja","fi":"Päiväntasaajan Guinea","hr":"Ekvatorska Gvineja","hu":"Egyenlítői-Guinea"} },
  { code: "GR", dial: "+30", names: {"en":"Greece","fr":"Grèce","de":"Griechenland","es":"Grecia","it":"Grecia","nl":"Griekenland","pl":"Grecja","ro":"Grecia","el":"Ελλάδα","bg":"Гърция","sk":"Grécko","sl":"Grčija","fi":"Kreikka","hr":"Grčka","hu":"Görögország"} },
  { code: "GT", dial: "+502", names: {"en":"Guatemala","fr":"Guatemala","de":"Guatemala","es":"Guatemala","it":"Guatemala","nl":"Guatemala","pl":"Gwatemala","ro":"Guatemala","el":"Γουατεμάλα","bg":"Гватемала","sk":"Guatemala","sl":"Gvatemala","fi":"Guatemala","hr":"Gvatemala","hu":"Guatemala"} },
  { code: "GU", dial: "+1671", names: {"en":"Guam","fr":"Guam","de":"Guam","es":"Guam","it":"Guam","nl":"Guam","pl":"Guam","ro":"Guam","el":"Γκουάμ","bg":"Гуам","sk":"Guam","sl":"Guam","fi":"Guam","hr":"Guam","hu":"Guam"} },
  { code: "GW", dial: "+245", names: {"en":"Guinea-Bissau","fr":"Guinée-Bissau","de":"Guinea-Bissau","es":"Guinea-Bisáu","it":"Guinea-Bissau","nl":"Guinee-Bissau","pl":"Gwinea Bissau","ro":"Guineea-Bissau","el":"Γουινέα Μπισάου","bg":"Гвинея-Бисау","sk":"Guinea-Bissau","sl":"Gvineja Bissau","fi":"Guinea-Bissau","hr":"Gvineja Bisau","hu":"Bissau-Guinea"} },
  { code: "GY", dial: "+592", names: {"en":"Guyana","fr":"Guyana","de":"Guyana","es":"Guyana","it":"Guyana","nl":"Guyana","pl":"Gujana","ro":"Guyana","el":"Γουιάνα","bg":"Гаяна","sk":"Guyana","sl":"Gvajana","fi":"Guyana","hr":"Gvajana","hu":"Guyana"} },
  { code: "HK", dial: "+852", names: {"en":"Hong Kong SAR China","fr":"R.A.S. chinoise de Hong Kong","de":"Sonderverwaltungsregion Hongkong","es":"RAE de Hong Kong (China)","it":"RAS di Hong Kong","nl":"Hongkong SAR van China","pl":"SRA Hongkong (Chiny)","ro":"R.A.S. Hong Kong, China","el":"Χονγκ Κονγκ ΕΔΠ Κίνας","bg":"Хонконг, САР на Китай","sk":"Hongkong – OAO Číny","sl":"Posebno upravno območje Ljudske republike Kitajske Hongkong","fi":"Hongkong – Kiinan erityishallintoalue","hr":"PUP Hong Kong Kina","hu":"Hongkong KKT"} },
  { code: "HN", dial: "+504", names: {"en":"Honduras","fr":"Honduras","de":"Honduras","es":"Honduras","it":"Honduras","nl":"Honduras","pl":"Honduras","ro":"Honduras","el":"Ονδούρα","bg":"Хондурас","sk":"Honduras","sl":"Honduras","fi":"Honduras","hr":"Honduras","hu":"Honduras"} },
  { code: "HR", dial: "+385", names: {"en":"Croatia","fr":"Croatie","de":"Kroatien","es":"Croacia","it":"Croazia","nl":"Kroatië","pl":"Chorwacja","ro":"Croația","el":"Κροατία","bg":"Хърватия","sk":"Chorvátsko","sl":"Hrvaška","fi":"Kroatia","hr":"Hrvatska","hu":"Horvátország"} },
  { code: "HT", dial: "+509", names: {"en":"Haiti","fr":"Haïti","de":"Haiti","es":"Haití","it":"Haiti","nl":"Haïti","pl":"Haiti","ro":"Haiti","el":"Αϊτή","bg":"Хаити","sk":"Haiti","sl":"Haiti","fi":"Haiti","hr":"Haiti","hu":"Haiti"} },
  { code: "HU", dial: "+36", names: {"en":"Hungary","fr":"Hongrie","de":"Ungarn","es":"Hungría","it":"Ungheria","nl":"Hongarije","pl":"Węgry","ro":"Ungaria","el":"Ουγγαρία","bg":"Унгария","sk":"Maďarsko","sl":"Madžarska","fi":"Unkari","hr":"Mađarska","hu":"Magyarország"} },
  { code: "ID", dial: "+62", names: {"en":"Indonesia","fr":"Indonésie","de":"Indonesien","es":"Indonesia","it":"Indonesia","nl":"Indonesië","pl":"Indonezja","ro":"Indonezia","el":"Ινδονησία","bg":"Индонезия","sk":"Indonézia","sl":"Indonezija","fi":"Indonesia","hr":"Indonezija","hu":"Indonézia"} },
  { code: "IE", dial: "+353", names: {"en":"Ireland","fr":"Irlande","de":"Irland","es":"Irlanda","it":"Irlanda","nl":"Ierland","pl":"Irlandia","ro":"Irlanda","el":"Ιρλανδία","bg":"Ирландия","sk":"Írsko","sl":"Irska","fi":"Irlanti","hr":"Irska","hu":"Írország"} },
  { code: "IL", dial: "+972", names: {"en":"Israel","fr":"Israël","de":"Israel","es":"Israel","it":"Israele","nl":"Israël","pl":"Izrael","ro":"Israel","el":"Ισραήλ","bg":"Израел","sk":"Izrael","sl":"Izrael","fi":"Israel","hr":"Izrael","hu":"Izrael"} },
  { code: "IM", dial: "+44", names: {"en":"Isle of Man","fr":"Île de Man","de":"Isle of Man","es":"Isla de Man","it":"Isola di Man","nl":"Isle of Man","pl":"Wyspa Man","ro":"Insula Man","el":"Νήσος του Μαν","bg":"остров Ман","sk":"Ostrov Man","sl":"Otok Man","fi":"Mansaari","hr":"Otok Man","hu":"Man-sziget"} },
  { code: "IN", dial: "+91", names: {"en":"India","fr":"Inde","de":"Indien","es":"India","it":"India","nl":"India","pl":"Indie","ro":"India","el":"Ινδία","bg":"Индия","sk":"India","sl":"Indija","fi":"Intia","hr":"Indija","hu":"India"} },
  { code: "IO", dial: "+246", names: {"en":"British Indian Ocean Territory","fr":"Territoire britannique de l’océan Indien","de":"Britisches Territorium im Indischen Ozean","es":"Territorio Británico del Océano Índico","it":"Territorio Britannico dell’Oceano Indiano","nl":"Brits Indische Oceaanterritorium","pl":"Brytyjskie Terytorium Oceanu Indyjskiego","ro":"Teritoriul Britanic din Oceanul Indian","el":"Βρετανικά Εδάφη Ινδικού Ωκεανού","bg":"Британска територия в Индийския океан","sk":"Britské indickooceánske územie","sl":"Britansko ozemlje v Indijskem oceanu","fi":"Brittiläinen Intian valtameren alue","hr":"Britanski Indijskooceanski Teritorij","hu":"Brit Indiai-óceáni Terület"} },
  { code: "IQ", dial: "+964", names: {"en":"Iraq","fr":"Irak","de":"Irak","es":"Irak","it":"Iraq","nl":"Irak","pl":"Irak","ro":"Irak","el":"Ιράκ","bg":"Ирак","sk":"Irak","sl":"Irak","fi":"Irak","hr":"Irak","hu":"Irak"} },
  { code: "IR", dial: "+98", names: {"en":"Iran","fr":"Iran","de":"Iran","es":"Irán","it":"Iran","nl":"Iran","pl":"Iran","ro":"Iran","el":"Ιράν","bg":"Иран","sk":"Irán","sl":"Iran","fi":"Iran","hr":"Iran","hu":"Irán"} },
  { code: "IS", dial: "+354", names: {"en":"Iceland","fr":"Islande","de":"Island","es":"Islandia","it":"Islanda","nl":"IJsland","pl":"Islandia","ro":"Islanda","el":"Ισλανδία","bg":"Исландия","sk":"Island","sl":"Islandija","fi":"Islanti","hr":"Island","hu":"Izland"} },
  { code: "IT", dial: "+39", names: {"en":"Italy","fr":"Italie","de":"Italien","es":"Italia","it":"Italia","nl":"Italië","pl":"Włochy","ro":"Italia","el":"Ιταλία","bg":"Италия","sk":"Taliansko","sl":"Italija","fi":"Italia","hr":"Italija","hu":"Olaszország"} },
  { code: "JE", dial: "+44", names: {"en":"Jersey","fr":"Jersey","de":"Jersey","es":"Jersey","it":"Jersey","nl":"Jersey","pl":"Jersey","ro":"Jersey","el":"Τζέρζι","bg":"Джърси","sk":"Jersey","sl":"Jersey","fi":"Jersey","hr":"Jersey","hu":"Jersey"} },
  { code: "JM", dial: "+1876", names: {"en":"Jamaica","fr":"Jamaïque","de":"Jamaika","es":"Jamaica","it":"Giamaica","nl":"Jamaica","pl":"Jamajka","ro":"Jamaica","el":"Τζαμάικα","bg":"Ямайка","sk":"Jamajka","sl":"Jamajka","fi":"Jamaika","hr":"Jamajka","hu":"Jamaica"} },
  { code: "JO", dial: "+962", names: {"en":"Jordan","fr":"Jordanie","de":"Jordanien","es":"Jordania","it":"Giordania","nl":"Jordanië","pl":"Jordania","ro":"Iordania","el":"Ιορδανία","bg":"Йордания","sk":"Jordánsko","sl":"Jordanija","fi":"Jordania","hr":"Jordan","hu":"Jordánia"} },
  { code: "JP", dial: "+81", names: {"en":"Japan","fr":"Japon","de":"Japan","es":"Japón","it":"Giappone","nl":"Japan","pl":"Japonia","ro":"Japonia","el":"Ιαπωνία","bg":"Япония","sk":"Japonsko","sl":"Japonska","fi":"Japani","hr":"Japan","hu":"Japán"} },
  { code: "KE", dial: "+254", names: {"en":"Kenya","fr":"Kenya","de":"Kenia","es":"Kenia","it":"Kenya","nl":"Kenia","pl":"Kenia","ro":"Kenya","el":"Κένυα","bg":"Кения","sk":"Keňa","sl":"Kenija","fi":"Kenia","hr":"Kenija","hu":"Kenya"} },
  { code: "KG", dial: "+996", names: {"en":"Kyrgyzstan","fr":"Kirghizstan","de":"Kirgisistan","es":"Kirguistán","it":"Kirghizistan","nl":"Kirgizië","pl":"Kirgistan","ro":"Kârgâzstan","el":"Κιργιστάν","bg":"Киргизстан","sk":"Kirgizsko","sl":"Kirgizistan","fi":"Kirgisia","hr":"Kirgistan","hu":"Kirgizisztán"} },
  { code: "KH", dial: "+855", names: {"en":"Cambodia","fr":"Cambodge","de":"Kambodscha","es":"Camboya","it":"Cambogia","nl":"Cambodja","pl":"Kambodża","ro":"Cambodgia","el":"Καμπότζη","bg":"Камбоджа","sk":"Kambodža","sl":"Kambodža","fi":"Kambodža","hr":"Kambodža","hu":"Kambodzsa"} },
  { code: "KI", dial: "+686", names: {"en":"Kiribati","fr":"Kiribati","de":"Kiribati","es":"Kiribati","it":"Kiribati","nl":"Kiribati","pl":"Kiribati","ro":"Kiribati","el":"Κιριμπάτι","bg":"Кирибати","sk":"Kiribati","sl":"Kiribati","fi":"Kiribati","hr":"Kiribati","hu":"Kiribati"} },
  { code: "KM", dial: "+269", names: {"en":"Comoros","fr":"Comores","de":"Komoren","es":"Comoras","it":"Comore","nl":"Comoren","pl":"Komory","ro":"Comore","el":"Κομόρες","bg":"Коморски острови","sk":"Komory","sl":"Komori","fi":"Komorit","hr":"Komori","hu":"Comore-szigetek"} },
  { code: "KN", dial: "+1869", names: {"en":"St. Kitts & Nevis","fr":"Saint-Christophe-et-Niévès","de":"St. Kitts und Nevis","es":"San Cristóbal y Nieves","it":"Saint Kitts e Nevis","nl":"Saint Kitts en Nevis","pl":"Saint Kitts i Nevis","ro":"Saint Kitts și Nevis","el":"Σεν Κιτς και Νέβις","bg":"Сейнт Китс и Невис","sk":"Svätý Krištof a Nevis","sl":"Saint Kitts in Nevis","fi":"Saint Kitts ja Nevis","hr":"Sveti Kristofor i Nevis","hu":"Saint Kitts és Nevis"} },
  { code: "KP", dial: "+850", names: {"en":"North Korea","fr":"Corée du Nord","de":"Nordkorea","es":"Corea del Norte","it":"Corea del Nord","nl":"Noord-Korea","pl":"Korea Północna","ro":"Coreea de Nord","el":"Βόρεια Κορέα","bg":"Северна Корея","sk":"Severná Kórea","sl":"Severna Koreja","fi":"Pohjois-Korea","hr":"Sjeverna Koreja","hu":"Észak-Korea"} },
  { code: "KR", dial: "+82", names: {"en":"South Korea","fr":"Corée du Sud","de":"Südkorea","es":"Corea del Sur","it":"Corea del Sud","nl":"Zuid-Korea","pl":"Korea Południowa","ro":"Coreea de Sud","el":"Νότια Κορέα","bg":"Южна Корея","sk":"Južná Kórea","sl":"Južna Koreja","fi":"Etelä-Korea","hr":"Južna Koreja","hu":"Dél-Korea"} },
  { code: "KW", dial: "+965", names: {"en":"Kuwait","fr":"Koweït","de":"Kuwait","es":"Kuwait","it":"Kuwait","nl":"Koeweit","pl":"Kuwejt","ro":"Kuweit","el":"Κουβέιτ","bg":"Кувейт","sk":"Kuvajt","sl":"Kuvajt","fi":"Kuwait","hr":"Kuvajt","hu":"Kuvait"} },
  { code: "KY", dial: "+1345", names: {"en":"Cayman Islands","fr":"Îles Caïmans","de":"Kaimaninseln","es":"Islas Caimán","it":"Isole Cayman","nl":"Kaaimaneilanden","pl":"Kajmany","ro":"Insulele Cayman","el":"Νήσοι Κέιμαν","bg":"Кайманови острови","sk":"Kajmanie ostrovy","sl":"Kajmanski otoki","fi":"Caymansaaret","hr":"Kajmanski Otoci","hu":"Kajmán-szigetek"} },
  { code: "KZ", dial: "+7", names: {"en":"Kazakhstan","fr":"Kazakhstan","de":"Kasachstan","es":"Kazajistán","it":"Kazakistan","nl":"Kazachstan","pl":"Kazachstan","ro":"Kazahstan","el":"Καζακστάν","bg":"Казахстан","sk":"Kazachstan","sl":"Kazahstan","fi":"Kazakstan","hr":"Kazahstan","hu":"Kazahsztán"} },
  { code: "LA", dial: "+856", names: {"en":"Laos","fr":"Laos","de":"Laos","es":"Laos","it":"Laos","nl":"Laos","pl":"Laos","ro":"Laos","el":"Λάος","bg":"Лаос","sk":"Laos","sl":"Laos","fi":"Laos","hr":"Laos","hu":"Laosz"} },
  { code: "LB", dial: "+961", names: {"en":"Lebanon","fr":"Liban","de":"Libanon","es":"Líbano","it":"Libano","nl":"Libanon","pl":"Liban","ro":"Liban","el":"Λίβανος","bg":"Ливан","sk":"Libanon","sl":"Libanon","fi":"Libanon","hr":"Libanon","hu":"Libanon"} },
  { code: "LC", dial: "+1758", names: {"en":"St. Lucia","fr":"Sainte-Lucie","de":"St. Lucia","es":"Santa Lucía","it":"Saint Lucia","nl":"Saint Lucia","pl":"Saint Lucia","ro":"Sfânta Lucia","el":"Αγία Λουκία","bg":"Сейнт Лусия","sk":"Svätá Lucia","sl":"Saint Lucia","fi":"Saint Lucia","hr":"Sveta Lucija","hu":"Saint Lucia"} },
  { code: "LI", dial: "+423", names: {"en":"Liechtenstein","fr":"Liechtenstein","de":"Liechtenstein","es":"Liechtenstein","it":"Liechtenstein","nl":"Liechtenstein","pl":"Liechtenstein","ro":"Liechtenstein","el":"Λιχτενστάιν","bg":"Лихтенщайн","sk":"Lichtenštajnsko","sl":"Lihtenštajn","fi":"Liechtenstein","hr":"Lihtenštajn","hu":"Liechtenstein"} },
  { code: "LK", dial: "+94", names: {"en":"Sri Lanka","fr":"Sri Lanka","de":"Sri Lanka","es":"Sri Lanka","it":"Sri Lanka","nl":"Sri Lanka","pl":"Sri Lanka","ro":"Sri Lanka","el":"Σρι Λάνκα","bg":"Шри Ланка","sk":"Srí Lanka","sl":"Šrilanka","fi":"Sri Lanka","hr":"Šri Lanka","hu":"Srí Lanka"} },
  { code: "LR", dial: "+231", names: {"en":"Liberia","fr":"Liberia","de":"Liberia","es":"Liberia","it":"Liberia","nl":"Liberia","pl":"Liberia","ro":"Liberia","el":"Λιβερία","bg":"Либерия","sk":"Libéria","sl":"Liberija","fi":"Liberia","hr":"Liberija","hu":"Libéria"} },
  { code: "LS", dial: "+266", names: {"en":"Lesotho","fr":"Lesotho","de":"Lesotho","es":"Lesoto","it":"Lesotho","nl":"Lesotho","pl":"Lesotho","ro":"Lesotho","el":"Λεσότο","bg":"Лесото","sk":"Lesotho","sl":"Lesoto","fi":"Lesotho","hr":"Lesoto","hu":"Lesotho"} },
  { code: "LT", dial: "+370", names: {"en":"Lithuania","fr":"Lituanie","de":"Litauen","es":"Lituania","it":"Lituania","nl":"Litouwen","pl":"Litwa","ro":"Lituania","el":"Λιθουανία","bg":"Литва","sk":"Litva","sl":"Litva","fi":"Liettua","hr":"Litva","hu":"Litvánia"} },
  { code: "LU", dial: "+352", names: {"en":"Luxembourg","fr":"Luxembourg","de":"Luxemburg","es":"Luxemburgo","it":"Lussemburgo","nl":"Luxemburg","pl":"Luksemburg","ro":"Luxemburg","el":"Λουξεμβούργο","bg":"Люксембург","sk":"Luxembursko","sl":"Luksemburg","fi":"Luxemburg","hr":"Luksemburg","hu":"Luxemburg"} },
  { code: "LV", dial: "+371", names: {"en":"Latvia","fr":"Lettonie","de":"Lettland","es":"Letonia","it":"Lettonia","nl":"Letland","pl":"Łotwa","ro":"Letonia","el":"Λετονία","bg":"Латвия","sk":"Lotyšsko","sl":"Latvija","fi":"Latvia","hr":"Latvija","hu":"Lettország"} },
  { code: "LY", dial: "+218", names: {"en":"Libya","fr":"Libye","de":"Libyen","es":"Libia","it":"Libia","nl":"Libië","pl":"Libia","ro":"Libia","el":"Λιβύη","bg":"Либия","sk":"Líbya","sl":"Libija","fi":"Libya","hr":"Libija","hu":"Líbia"} },
  { code: "MA", dial: "+212", names: {"en":"Morocco","fr":"Maroc","de":"Marokko","es":"Marruecos","it":"Marocco","nl":"Marokko","pl":"Maroko","ro":"Maroc","el":"Μαρόκο","bg":"Мароко","sk":"Maroko","sl":"Maroko","fi":"Marokko","hr":"Maroko","hu":"Marokkó"} },
  { code: "MC", dial: "+377", names: {"en":"Monaco","fr":"Monaco","de":"Monaco","es":"Mónaco","it":"Monaco","nl":"Monaco","pl":"Monako","ro":"Monaco","el":"Μονακό","bg":"Монако","sk":"Monako","sl":"Monako","fi":"Monaco","hr":"Monako","hu":"Monaco"} },
  { code: "MD", dial: "+373", names: {"en":"Moldova","fr":"Moldavie","de":"Republik Moldau","es":"Moldavia","it":"Moldavia","nl":"Moldavië","pl":"Mołdawia","ro":"Republica Moldova","el":"Μολδαβία","bg":"Молдова","sk":"Moldavsko","sl":"Moldavija","fi":"Moldova","hr":"Moldavija","hu":"Moldova"} },
  { code: "ME", dial: "+382", names: {"en":"Montenegro","fr":"Monténégro","de":"Montenegro","es":"Montenegro","it":"Montenegro","nl":"Montenegro","pl":"Czarnogóra","ro":"Muntenegru","el":"Μαυροβούνιο","bg":"Черна гора","sk":"Čierna Hora","sl":"Črna gora","fi":"Montenegro","hr":"Crna Gora","hu":"Montenegró"} },
  { code: "MF", dial: "+590", names: {"en":"St. Martin","fr":"Saint-Martin","de":"St. Martin","es":"San Martín","it":"Saint Martin","nl":"Saint-Martin","pl":"Saint-Martin","ro":"Sfântul Martin","el":"Άγιος Μαρτίνος (Γαλλικό τμήμα)","bg":"Сен Мартен","sk":"Svätý Martin (fr.)","sl":"Saint Martin","fi":"Saint-Martin","hr":"Saint Martin","hu":"Saint Martin"} },
  { code: "MG", dial: "+261", names: {"en":"Madagascar","fr":"Madagascar","de":"Madagaskar","es":"Madagascar","it":"Madagascar","nl":"Madagaskar","pl":"Madagaskar","ro":"Madagascar","el":"Μαδαγασκάρη","bg":"Мадагаскар","sk":"Madagaskar","sl":"Madagaskar","fi":"Madagaskar","hr":"Madagaskar","hu":"Madagaszkár"} },
  { code: "MH", dial: "+692", names: {"en":"Marshall Islands","fr":"Îles Marshall","de":"Marshallinseln","es":"Islas Marshall","it":"Isole Marshall","nl":"Marshalleilanden","pl":"Wyspy Marshalla","ro":"Insulele Marshall","el":"Νήσοι Μάρσαλ","bg":"Маршалови острови","sk":"Marshallove ostrovy","sl":"Marshallovi otoki","fi":"Marshallinsaaret","hr":"Maršalovi Otoci","hu":"Marshall-szigetek"} },
  { code: "MK", dial: "+389", names: {"en":"North Macedonia","fr":"Macédoine du Nord","de":"Nordmazedonien","es":"Macedonia del Norte","it":"Macedonia del Nord","nl":"Noord-Macedonië","pl":"Macedonia Północna","ro":"Macedonia de Nord","el":"Βόρεια Μακεδονία","bg":"Северна Македония","sk":"Severné Macedónsko","sl":"Severna Makedonija","fi":"Pohjois-Makedonia","hr":"Sjeverna Makedonija","hu":"Észak-Macedónia"} },
  { code: "ML", dial: "+223", names: {"en":"Mali","fr":"Mali","de":"Mali","es":"Mali","it":"Mali","nl":"Mali","pl":"Mali","ro":"Mali","el":"Μάλι","bg":"Мали","sk":"Mali","sl":"Mali","fi":"Mali","hr":"Mali","hu":"Mali"} },
  { code: "MM", dial: "+95", names: {"en":"Myanmar (Burma)","fr":"Myanmar (Birmanie)","de":"Myanmar","es":"Myanmar (Birmania)","it":"Myanmar (Birmania)","nl":"Myanmar (Birma)","pl":"Mjanma (Birma)","ro":"Myanmar (Birmania)","el":"Μιανμάρ (Βιρμανία)","bg":"Мианмар (Бирма)","sk":"Mjanmarsko","sl":"Mjanmar (Burma)","fi":"Myanmar (Burma)","hr":"Mjanmar (Burma)","hu":"Mianmar"} },
  { code: "MN", dial: "+976", names: {"en":"Mongolia","fr":"Mongolie","de":"Mongolei","es":"Mongolia","it":"Mongolia","nl":"Mongolië","pl":"Mongolia","ro":"Mongolia","el":"Μογγολία","bg":"Монголия","sk":"Mongolsko","sl":"Mongolija","fi":"Mongolia","hr":"Mongolija","hu":"Mongólia"} },
  { code: "MO", dial: "+853", names: {"en":"Macao SAR China","fr":"R.A.S. chinoise de Macao","de":"Sonderverwaltungsregion Macau","es":"RAE de Macao (China)","it":"RAS di Macao","nl":"Macau SAR van China","pl":"SRA Makau (Chiny)","ro":"R.A.S. Macao, China","el":"Μακάο ΕΔΠ Κίνας","bg":"Макао, САР на Китай","sk":"Macao – OAO Číny","sl":"Posebno upravno območje Ljudske republike Kitajske Macao","fi":"Macao – Kiinan erityishallintoalue","hr":"PUP Makao Kina","hu":"Makaó KKT"} },
  { code: "MP", dial: "+1670", names: {"en":"Northern Mariana Islands","fr":"Îles Mariannes du Nord","de":"Nördliche Marianen","es":"Islas Marianas del Norte","it":"Isole Marianne Settentrionali","nl":"Noordelijke Marianen","pl":"Mariany Północne","ro":"Insulele Mariane de Nord","el":"Νήσοι Βόρειες Μαριάνες","bg":"Северни Мариански острови","sk":"Severné Mariány","sl":"Severni Marianski otoki","fi":"Pohjois-Mariaanit","hr":"Sjevernomarijanski Otoci","hu":"Északi Mariana-szigetek"} },
  { code: "MQ", dial: "+596", names: {"en":"Martinique","fr":"Martinique","de":"Martinique","es":"Martinica","it":"Martinica","nl":"Martinique","pl":"Martynika","ro":"Martinica","el":"Μαρτινίκα","bg":"Мартиника","sk":"Martinik","sl":"Martinik","fi":"Martinique","hr":"Martinik","hu":"Martinique"} },
  { code: "MR", dial: "+222", names: {"en":"Mauritania","fr":"Mauritanie","de":"Mauretanien","es":"Mauritania","it":"Mauritania","nl":"Mauritanië","pl":"Mauretania","ro":"Mauritania","el":"Μαυριτανία","bg":"Мавритания","sk":"Mauritánia","sl":"Mavretanija","fi":"Mauritania","hr":"Mauretanija","hu":"Mauritánia"} },
  { code: "MS", dial: "+1664", names: {"en":"Montserrat","fr":"Montserrat","de":"Montserrat","es":"Montserrat","it":"Montserrat","nl":"Montserrat","pl":"Montserrat","ro":"Montserrat","el":"Μονσεράτ","bg":"Монтсерат","sk":"Montserrat","sl":"Montserrat","fi":"Montserrat","hr":"Montserrat","hu":"Montserrat"} },
  { code: "MT", dial: "+356", names: {"en":"Malta","fr":"Malte","de":"Malta","es":"Malta","it":"Malta","nl":"Malta","pl":"Malta","ro":"Malta","el":"Μάλτα","bg":"Малта","sk":"Malta","sl":"Malta","fi":"Malta","hr":"Malta","hu":"Málta"} },
  { code: "MU", dial: "+230", names: {"en":"Mauritius","fr":"Maurice","de":"Mauritius","es":"Mauricio","it":"Mauritius","nl":"Mauritius","pl":"Mauritius","ro":"Mauritius","el":"Μαυρίκιος","bg":"Мавриций","sk":"Maurícius","sl":"Mauritius","fi":"Mauritius","hr":"Mauricijus","hu":"Mauritius"} },
  { code: "MV", dial: "+960", names: {"en":"Maldives","fr":"Maldives","de":"Malediven","es":"Maldivas","it":"Maldive","nl":"Maldiven","pl":"Malediwy","ro":"Maldive","el":"Μαλδίβες","bg":"Малдиви","sk":"Maldivy","sl":"Maldivi","fi":"Malediivit","hr":"Maldivi","hu":"Maldív-szigetek"} },
  { code: "MW", dial: "+265", names: {"en":"Malawi","fr":"Malawi","de":"Malawi","es":"Malaui","it":"Malawi","nl":"Malawi","pl":"Malawi","ro":"Malawi","el":"Μαλάουι","bg":"Малави","sk":"Malawi","sl":"Malavi","fi":"Malawi","hr":"Malavi","hu":"Malawi"} },
  { code: "MX", dial: "+52", names: {"en":"Mexico","fr":"Mexique","de":"Mexiko","es":"México","it":"Messico","nl":"Mexico","pl":"Meksyk","ro":"Mexic","el":"Μεξικό","bg":"Мексико","sk":"Mexiko","sl":"Mehika","fi":"Meksiko","hr":"Meksiko","hu":"Mexikó"} },
  { code: "MY", dial: "+60", names: {"en":"Malaysia","fr":"Malaisie","de":"Malaysia","es":"Malasia","it":"Malaysia","nl":"Maleisië","pl":"Malezja","ro":"Malaysia","el":"Μαλαισία","bg":"Малайзия","sk":"Malajzia","sl":"Malezija","fi":"Malesia","hr":"Malezija","hu":"Malajzia"} },
  { code: "MZ", dial: "+258", names: {"en":"Mozambique","fr":"Mozambique","de":"Mosambik","es":"Mozambique","it":"Mozambico","nl":"Mozambique","pl":"Mozambik","ro":"Mozambic","el":"Μοζαμβίκη","bg":"Мозамбик","sk":"Mozambik","sl":"Mozambik","fi":"Mosambik","hr":"Mozambik","hu":"Mozambik"} },
  { code: "NA", dial: "+264", names: {"en":"Namibia","fr":"Namibie","de":"Namibia","es":"Namibia","it":"Namibia","nl":"Namibië","pl":"Namibia","ro":"Namibia","el":"Ναμίμπια","bg":"Намибия","sk":"Namíbia","sl":"Namibija","fi":"Namibia","hr":"Namibija","hu":"Namíbia"} },
  { code: "NC", dial: "+687", names: {"en":"New Caledonia","fr":"Nouvelle-Calédonie","de":"Neukaledonien","es":"Nueva Caledonia","it":"Nuova Caledonia","nl":"Nieuw-Caledonië","pl":"Nowa Kaledonia","ro":"Noua Caledonie","el":"Νέα Καληδονία","bg":"Нова Каледония","sk":"Nová Kaledónia","sl":"Nova Kaledonija","fi":"Uusi-Kaledonia","hr":"Nova Kaledonija","hu":"Új-Kaledónia"} },
  { code: "NE", dial: "+227", names: {"en":"Niger","fr":"Niger","de":"Niger","es":"Níger","it":"Niger","nl":"Niger","pl":"Niger","ro":"Niger","el":"Νίγηρας","bg":"Нигер","sk":"Niger","sl":"Niger","fi":"Niger","hr":"Niger","hu":"Niger"} },
  { code: "NF", dial: "+672", names: {"en":"Norfolk Island","fr":"Île Norfolk","de":"Norfolkinsel","es":"Isla Norfolk","it":"Isola Norfolk","nl":"Norfolk","pl":"Norfolk","ro":"Insula Norfolk","el":"Νήσος Νόρφολκ","bg":"остров Норфолк","sk":"Norfolk","sl":"Norfolški otok","fi":"Norfolkinsaari","hr":"Otok Norfolk","hu":"Norfolk-sziget"} },
  { code: "NG", dial: "+234", names: {"en":"Nigeria","fr":"Nigeria","de":"Nigeria","es":"Nigeria","it":"Nigeria","nl":"Nigeria","pl":"Nigeria","ro":"Nigeria","el":"Νιγηρία","bg":"Нигерия","sk":"Nigéria","sl":"Nigerija","fi":"Nigeria","hr":"Nigerija","hu":"Nigéria"} },
  { code: "NI", dial: "+505", names: {"en":"Nicaragua","fr":"Nicaragua","de":"Nicaragua","es":"Nicaragua","it":"Nicaragua","nl":"Nicaragua","pl":"Nikaragua","ro":"Nicaragua","el":"Νικαράγουα","bg":"Никарагуа","sk":"Nikaragua","sl":"Nikaragva","fi":"Nicaragua","hr":"Nikaragva","hu":"Nicaragua"} },
  { code: "NL", dial: "+31", names: {"en":"Netherlands","fr":"Pays-Bas","de":"Niederlande","es":"Países Bajos","it":"Paesi Bassi","nl":"Nederland","pl":"Holandia","ro":"Țările de Jos","el":"Κάτω Χώρες","bg":"Нидерландия","sk":"Holandsko","sl":"Nizozemska","fi":"Alankomaat","hr":"Nizozemska","hu":"Hollandia"} },
  { code: "NO", dial: "+47", names: {"en":"Norway","fr":"Norvège","de":"Norwegen","es":"Noruega","it":"Norvegia","nl":"Noorwegen","pl":"Norwegia","ro":"Norvegia","el":"Νορβηγία","bg":"Норвегия","sk":"Nórsko","sl":"Norveška","fi":"Norja","hr":"Norveška","hu":"Norvégia"} },
  { code: "NP", dial: "+977", names: {"en":"Nepal","fr":"Népal","de":"Nepal","es":"Nepal","it":"Nepal","nl":"Nepal","pl":"Nepal","ro":"Nepal","el":"Νεπάλ","bg":"Непал","sk":"Nepál","sl":"Nepal","fi":"Nepal","hr":"Nepal","hu":"Nepál"} },
  { code: "NR", dial: "+674", names: {"en":"Nauru","fr":"Nauru","de":"Nauru","es":"Nauru","it":"Nauru","nl":"Nauru","pl":"Nauru","ro":"Nauru","el":"Ναουρού","bg":"Науру","sk":"Nauru","sl":"Nauru","fi":"Nauru","hr":"Nauru","hu":"Nauru"} },
  { code: "NU", dial: "+683", names: {"en":"Niue","fr":"Niue","de":"Niue","es":"Niue","it":"Niue","nl":"Niue","pl":"Niue","ro":"Niue","el":"Νιούε","bg":"Ниуе","sk":"Niue","sl":"Niue","fi":"Niue","hr":"Niue","hu":"Niue"} },
  { code: "NZ", dial: "+64", names: {"en":"New Zealand","fr":"Nouvelle-Zélande","de":"Neuseeland","es":"Nueva Zelanda","it":"Nuova Zelanda","nl":"Nieuw-Zeeland","pl":"Nowa Zelandia","ro":"Noua Zeelandă","el":"Νέα Ζηλανδία","bg":"Нова Зеландия","sk":"Nový Zéland","sl":"Nova Zelandija","fi":"Uusi-Seelanti","hr":"Novi Zeland","hu":"Új-Zéland"} },
  { code: "OM", dial: "+968", names: {"en":"Oman","fr":"Oman","de":"Oman","es":"Omán","it":"Oman","nl":"Oman","pl":"Oman","ro":"Oman","el":"Ομάν","bg":"Оман","sk":"Omán","sl":"Oman","fi":"Oman","hr":"Oman","hu":"Omán"} },
  { code: "PA", dial: "+507", names: {"en":"Panama","fr":"Panama","de":"Panama","es":"Panamá","it":"Panama","nl":"Panama","pl":"Panama","ro":"Panama","el":"Παναμάς","bg":"Панама","sk":"Panama","sl":"Panama","fi":"Panama","hr":"Panama","hu":"Panama"} },
  { code: "PE", dial: "+51", names: {"en":"Peru","fr":"Pérou","de":"Peru","es":"Perú","it":"Perù","nl":"Peru","pl":"Peru","ro":"Peru","el":"Περού","bg":"Перу","sk":"Peru","sl":"Peru","fi":"Peru","hr":"Peru","hu":"Peru"} },
  { code: "PF", dial: "+689", names: {"en":"French Polynesia","fr":"Polynésie française","de":"Französisch-Polynesien","es":"Polinesia Francesa","it":"Polinesia Francese","nl":"Frans-Polynesië","pl":"Polinezja Francuska","ro":"Polinezia Franceză","el":"Γαλλική Πολυνησία","bg":"Френска Полинезия","sk":"Francúzska Polynézia","sl":"Francoska Polinezija","fi":"Ranskan Polynesia","hr":"Francuska Polinezija","hu":"Francia Polinézia"} },
  { code: "PG", dial: "+675", names: {"en":"Papua New Guinea","fr":"Papouasie-Nouvelle-Guinée","de":"Papua-Neuguinea","es":"Papúa Nueva Guinea","it":"Papua Nuova Guinea","nl":"Papoea-Nieuw-Guinea","pl":"Papua-Nowa Gwinea","ro":"Papua-Noua Guinee","el":"Παπούα Νέα Γουινέα","bg":"Папуа-Нова Гвинея","sk":"Papua-Nová Guinea","sl":"Papua Nova Gvineja","fi":"Papua-Uusi-Guinea","hr":"Papua Nova Gvineja","hu":"Pápua Új-Guinea"} },
  { code: "PH", dial: "+63", names: {"en":"Philippines","fr":"Philippines","de":"Philippinen","es":"Filipinas","it":"Filippine","nl":"Filipijnen","pl":"Filipiny","ro":"Filipine","el":"Φιλιππίνες","bg":"Филипини","sk":"Filipíny","sl":"Filipini","fi":"Filippiinit","hr":"Filipini","hu":"Fülöp-szigetek"} },
  { code: "PK", dial: "+92", names: {"en":"Pakistan","fr":"Pakistan","de":"Pakistan","es":"Pakistán","it":"Pakistan","nl":"Pakistan","pl":"Pakistan","ro":"Pakistan","el":"Πακιστάν","bg":"Пакистан","sk":"Pakistan","sl":"Pakistan","fi":"Pakistan","hr":"Pakistan","hu":"Pakisztán"} },
  { code: "PL", dial: "+48", names: {"en":"Poland","fr":"Pologne","de":"Polen","es":"Polonia","it":"Polonia","nl":"Polen","pl":"Polska","ro":"Polonia","el":"Πολωνία","bg":"Полша","sk":"Poľsko","sl":"Poljska","fi":"Puola","hr":"Poljska","hu":"Lengyelország"} },
  { code: "PM", dial: "+508", names: {"en":"St. Pierre & Miquelon","fr":"Saint-Pierre-et-Miquelon","de":"St. Pierre und Miquelon","es":"San Pedro y Miquelón","it":"Saint-Pierre e Miquelon","nl":"Saint-Pierre en Miquelon","pl":"Saint-Pierre i Miquelon","ro":"Saint-Pierre și Miquelon","el":"Σεν Πιερ και Μικελόν","bg":"Сен Пиер и Микелон","sk":"Saint Pierre a Miquelon","sl":"Saint Pierre in Miquelon","fi":"Saint-Pierre ja Miquelon","hr":"Sveti Petar i Mikelon","hu":"Saint-Pierre és Miquelon"} },
  { code: "PR", dial: "+1787", names: {"en":"Puerto Rico","fr":"Porto Rico","de":"Puerto Rico","es":"Puerto Rico","it":"Portorico","nl":"Puerto Rico","pl":"Portoryko","ro":"Puerto Rico","el":"Πουέρτο Ρίκο","bg":"Пуерто Рико","sk":"Portoriko","sl":"Portoriko","fi":"Puerto Rico","hr":"Portoriko","hu":"Puerto Rico"} },
  { code: "PS", dial: "+970", names: {"en":"Palestinian Territories","fr":"Territoires palestiniens","de":"Palästinensische Autonomiegebiete","es":"Territorios Palestinos","it":"Territori Palestinesi","nl":"Palestijnse gebieden","pl":"Terytoria Palestyńskie","ro":"Teritoriile Palestiniene","el":"Παλαιστινιακά Εδάφη","bg":"Палестински територии","sk":"Palestínske územia","sl":"Palestinsko ozemlje","fi":"Palestiinalaisalue","hr":"Palestinsko područje","hu":"Palesztin Autonómia"} },
  { code: "PT", dial: "+351", names: {"en":"Portugal","fr":"Portugal","de":"Portugal","es":"Portugal","it":"Portogallo","nl":"Portugal","pl":"Portugalia","ro":"Portugalia","el":"Πορτογαλία","bg":"Португалия","sk":"Portugalsko","sl":"Portugalska","fi":"Portugali","hr":"Portugal","hu":"Portugália"} },
  { code: "PW", dial: "+680", names: {"en":"Palau","fr":"Palaos","de":"Palau","es":"Palaos","it":"Palau","nl":"Palau","pl":"Palau","ro":"Palau","el":"Παλάου","bg":"Палау","sk":"Palau","sl":"Palau","fi":"Palau","hr":"Palau","hu":"Palau"} },
  { code: "PY", dial: "+595", names: {"en":"Paraguay","fr":"Paraguay","de":"Paraguay","es":"Paraguay","it":"Paraguay","nl":"Paraguay","pl":"Paragwaj","ro":"Paraguay","el":"Παραγουάη","bg":"Парагвай","sk":"Paraguaj","sl":"Paragvaj","fi":"Paraguay","hr":"Paragvaj","hu":"Paraguay"} },
  { code: "QA", dial: "+974", names: {"en":"Qatar","fr":"Qatar","de":"Katar","es":"Catar","it":"Qatar","nl":"Qatar","pl":"Katar","ro":"Qatar","el":"Κατάρ","bg":"Катар","sk":"Katar","sl":"Katar","fi":"Qatar","hr":"Katar","hu":"Katar"} },
  { code: "RE", dial: "+262", names: {"en":"Réunion","fr":"La Réunion","de":"Réunion","es":"Reunión","it":"Riunione","nl":"Réunion","pl":"Reunion","ro":"Réunion","el":"Ρεϊνιόν","bg":"Реюнион","sk":"Réunion","sl":"Reunion","fi":"Réunion","hr":"Réunion","hu":"Réunion"} },
  { code: "RO", dial: "+40", names: {"en":"Romania","fr":"Roumanie","de":"Rumänien","es":"Rumanía","it":"Romania","nl":"Roemenië","pl":"Rumunia","ro":"România","el":"Ρουμανία","bg":"Румъния","sk":"Rumunsko","sl":"Romunija","fi":"Romania","hr":"Rumunjska","hu":"Románia"} },
  { code: "RS", dial: "+381", names: {"en":"Serbia","fr":"Serbie","de":"Serbien","es":"Serbia","it":"Serbia","nl":"Servië","pl":"Serbia","ro":"Serbia","el":"Σερβία","bg":"Сърбия","sk":"Srbsko","sl":"Srbija","fi":"Serbia","hr":"Srbija","hu":"Szerbia"} },
  { code: "RU", dial: "+7", names: {"en":"Russia","fr":"Russie","de":"Russland","es":"Rusia","it":"Russia","nl":"Rusland","pl":"Rosja","ro":"Rusia","el":"Ρωσία","bg":"Русия","sk":"Rusko","sl":"Rusija","fi":"Venäjä","hr":"Rusija","hu":"Oroszország"} },
  { code: "RW", dial: "+250", names: {"en":"Rwanda","fr":"Rwanda","de":"Ruanda","es":"Ruanda","it":"Ruanda","nl":"Rwanda","pl":"Rwanda","ro":"Rwanda","el":"Ρουάντα","bg":"Руанда","sk":"Rwanda","sl":"Ruanda","fi":"Ruanda","hr":"Ruanda","hu":"Ruanda"} },
  { code: "SA", dial: "+966", names: {"en":"Saudi Arabia","fr":"Arabie saoudite","de":"Saudi-Arabien","es":"Arabia Saudí","it":"Arabia Saudita","nl":"Saoedi-Arabië","pl":"Arabia Saudyjska","ro":"Arabia Saudită","el":"Σαουδική Αραβία","bg":"Саудитска Арабия","sk":"Saudská Arábia","sl":"Saudova Arabija","fi":"Saudi-Arabia","hr":"Saudijska Arabija","hu":"Szaúd-Arábia"} },
  { code: "SB", dial: "+677", names: {"en":"Solomon Islands","fr":"Îles Salomon","de":"Salomonen","es":"Islas Salomón","it":"Isole Salomone","nl":"Salomonseilanden","pl":"Wyspy Salomona","ro":"Insulele Solomon","el":"Νήσοι Σολομώντος","bg":"Соломонови острови","sk":"Šalamúnove ostrovy","sl":"Salomonovi otoki","fi":"Salomonsaaret","hr":"Salomonovi Otoci","hu":"Salamon-szigetek"} },
  { code: "SC", dial: "+248", names: {"en":"Seychelles","fr":"Seychelles","de":"Seychellen","es":"Seychelles","it":"Seychelles","nl":"Seychellen","pl":"Seszele","ro":"Seychelles","el":"Σεϋχέλλες","bg":"Сейшели","sk":"Seychely","sl":"Sejšeli","fi":"Seychellit","hr":"Sejšeli","hu":"Seychelle-szigetek"} },
  { code: "SD", dial: "+249", names: {"en":"Sudan","fr":"Soudan","de":"Sudan","es":"Sudán","it":"Sudan","nl":"Soedan","pl":"Sudan","ro":"Sudan","el":"Σουδάν","bg":"Судан","sk":"Sudán","sl":"Sudan","fi":"Sudan","hr":"Sudan","hu":"Szudán"} },
  { code: "SE", dial: "+46", names: {"en":"Sweden","fr":"Suède","de":"Schweden","es":"Suecia","it":"Svezia","nl":"Zweden","pl":"Szwecja","ro":"Suedia","el":"Σουηδία","bg":"Швеция","sk":"Švédsko","sl":"Švedska","fi":"Ruotsi","hr":"Švedska","hu":"Svédország"} },
  { code: "SG", dial: "+65", names: {"en":"Singapore","fr":"Singapour","de":"Singapur","es":"Singapur","it":"Singapore","nl":"Singapore","pl":"Singapur","ro":"Singapore","el":"Σιγκαπούρη","bg":"Сингапур","sk":"Singapur","sl":"Singapur","fi":"Singapore","hr":"Singapur","hu":"Szingapúr"} },
  { code: "SH", dial: "+290", names: {"en":"St. Helena","fr":"Sainte-Hélène","de":"St. Helena","es":"Santa Elena","it":"Sant’Elena","nl":"Sint-Helena","pl":"Wyspa Świętej Heleny","ro":"Sfânta Elena","el":"Αγία Ελένη","bg":"Света Елена","sk":"Svätá Helena","sl":"Sveta Helena","fi":"Saint Helena","hr":"Sveta Helena","hu":"Szent Ilona"} },
  { code: "SI", dial: "+386", names: {"en":"Slovenia","fr":"Slovénie","de":"Slowenien","es":"Eslovenia","it":"Slovenia","nl":"Slovenië","pl":"Słowenia","ro":"Slovenia","el":"Σλοβενία","bg":"Словения","sk":"Slovinsko","sl":"Slovenija","fi":"Slovenia","hr":"Slovenija","hu":"Szlovénia"} },
  { code: "SJ", dial: "+47", names: {"en":"Svalbard & Jan Mayen","fr":"Svalbard et Jan Mayen","de":"Spitzbergen und Jan Mayen","es":"Svalbard y Jan Mayen","it":"Svalbard e Jan Mayen","nl":"Spitsbergen en Jan Mayen","pl":"Svalbard i Jan Mayen","ro":"Svalbard și Jan Mayen","el":"Σβάλμπαρντ και Γιαν Μαγιέν","bg":"Свалбард и Ян Майен","sk":"Svalbard a Jan Mayen","sl":"Svalbard in Jan Mayen","fi":"Huippuvuoret ja Jan Mayen","hr":"Svalbard i Jan Mayen","hu":"Svalbard és Jan Mayen"} },
  { code: "SK", dial: "+421", names: {"en":"Slovakia","fr":"Slovaquie","de":"Slowakei","es":"Eslovaquia","it":"Slovacchia","nl":"Slowakije","pl":"Słowacja","ro":"Slovacia","el":"Σλοβακία","bg":"Словакия","sk":"Slovensko","sl":"Slovaška","fi":"Slovakia","hr":"Slovačka","hu":"Szlovákia"} },
  { code: "SL", dial: "+232", names: {"en":"Sierra Leone","fr":"Sierra Leone","de":"Sierra Leone","es":"Sierra Leona","it":"Sierra Leone","nl":"Sierra Leone","pl":"Sierra Leone","ro":"Sierra Leone","el":"Σιέρα Λεόνε","bg":"Сиера Леоне","sk":"Sierra Leone","sl":"Sierra Leone","fi":"Sierra Leone","hr":"Sijera Leone","hu":"Sierra Leone"} },
  { code: "SM", dial: "+378", names: {"en":"San Marino","fr":"Saint-Marin","de":"San Marino","es":"San Marino","it":"San Marino","nl":"San Marino","pl":"San Marino","ro":"San Marino","el":"Άγιος Μαρίνος","bg":"Сан Марино","sk":"San Maríno","sl":"San Marino","fi":"San Marino","hr":"San Marino","hu":"San Marino"} },
  { code: "SN", dial: "+221", names: {"en":"Senegal","fr":"Sénégal","de":"Senegal","es":"Senegal","it":"Senegal","nl":"Senegal","pl":"Senegal","ro":"Senegal","el":"Σενεγάλη","bg":"Сенегал","sk":"Senegal","sl":"Senegal","fi":"Senegal","hr":"Senegal","hu":"Szenegál"} },
  { code: "SO", dial: "+252", names: {"en":"Somalia","fr":"Somalie","de":"Somalia","es":"Somalia","it":"Somalia","nl":"Somalië","pl":"Somalia","ro":"Somalia","el":"Σομαλία","bg":"Сомалия","sk":"Somálsko","sl":"Somalija","fi":"Somalia","hr":"Somalija","hu":"Szomália"} },
  { code: "SR", dial: "+597", names: {"en":"Suriname","fr":"Suriname","de":"Suriname","es":"Surinam","it":"Suriname","nl":"Suriname","pl":"Surinam","ro":"Suriname","el":"Σουρινάμ","bg":"Суринам","sk":"Surinam","sl":"Surinam","fi":"Suriname","hr":"Surinam","hu":"Suriname"} },
  { code: "SS", dial: "+211", names: {"en":"South Sudan","fr":"Soudan du Sud","de":"Südsudan","es":"Sudán del Sur","it":"Sud Sudan","nl":"Zuid-Soedan","pl":"Sudan Południowy","ro":"Sudanul de Sud","el":"Νότιο Σουδάν","bg":"Южен Судан","sk":"Južný Sudán","sl":"Južni Sudan","fi":"Etelä-Sudan","hr":"Južni Sudan","hu":"Dél-Szudán"} },
  { code: "ST", dial: "+239", names: {"en":"São Tomé & Príncipe","fr":"Sao Tomé-et-Principe","de":"São Tomé und Príncipe","es":"Santo Tomé y Príncipe","it":"São Tomé e Príncipe","nl":"Sao Tomé en Principe","pl":"Wyspy Świętego Tomasza i Książęca","ro":"São Tomé și Príncipe","el":"Σάο Τομέ και Πρίνσιπε","bg":"Сао Томе и Принсипи","sk":"Svätý Tomáš a Princov ostrov","sl":"Sao Tome in Principe","fi":"São Tomé ja Príncipe","hr":"Sveti Toma i Princip","hu":"São Tomé és Príncipe"} },
  { code: "SV", dial: "+503", names: {"en":"El Salvador","fr":"Salvador","de":"El Salvador","es":"El Salvador","it":"El Salvador","nl":"El Salvador","pl":"Salwador","ro":"El Salvador","el":"Ελ Σαλβαδόρ","bg":"Салвадор","sk":"Salvádor","sl":"Salvador","fi":"El Salvador","hr":"Salvador","hu":"Salvador"} },
  { code: "SX", dial: "+1721", names: {"en":"Sint Maarten","fr":"Saint-Martin (partie néerlandaise)","de":"Sint Maarten","es":"Sint Maarten","it":"Sint Maarten","nl":"Sint-Maarten","pl":"Sint Maarten","ro":"Sint-Maarten","el":"Άγιος Μαρτίνος (Ολλανδικό τμήμα)","bg":"Синт Мартен","sk":"Svätý Martin (hol.)","sl":"Sint Maarten","fi":"Sint Maarten","hr":"Sint Maarten","hu":"Sint Maarten"} },
  { code: "SY", dial: "+963", names: {"en":"Syria","fr":"Syrie","de":"Syrien","es":"Siria","it":"Siria","nl":"Syrië","pl":"Syria","ro":"Siria","el":"Συρία","bg":"Сирия","sk":"Sýria","sl":"Sirija","fi":"Syyria","hr":"Sirija","hu":"Szíria"} },
  { code: "SZ", dial: "+268", names: {"en":"Eswatini","fr":"Eswatini","de":"Eswatini","es":"Esuatini","it":"Eswatini","nl":"Eswatini","pl":"Eswatini","ro":"Eswatini","el":"Εσουατίνι","bg":"Есватини","sk":"Eswatini","sl":"Esvatini","fi":"Eswatini","hr":"Esvatini","hu":"Szváziföld"} },
  { code: "TC", dial: "+1649", names: {"en":"Turks & Caicos Islands","fr":"Îles Turques-et-Caïques","de":"Turks- und Caicosinseln","es":"Islas Turcas y Caicos","it":"Isole Turks e Caicos","nl":"Turks- en Caicoseilanden","pl":"Turks i Caicos","ro":"Insulele Turks și Caicos","el":"Νήσοι Τερκς και Κάικος","bg":"острови Търкс и Кайкос","sk":"Turks a Caicos","sl":"Otoki Turks in Caicos","fi":"Turks- ja Caicossaaret","hr":"Otoci Turks i Caicos","hu":"Turks- és Caicos-szigetek"} },
  { code: "TD", dial: "+235", names: {"en":"Chad","fr":"Tchad","de":"Tschad","es":"Chad","it":"Ciad","nl":"Tsjaad","pl":"Czad","ro":"Ciad","el":"Τσαντ","bg":"Чад","sk":"Čad","sl":"Čad","fi":"Tšad","hr":"Čad","hu":"Csád"} },
  { code: "TG", dial: "+228", names: {"en":"Togo","fr":"Togo","de":"Togo","es":"Togo","it":"Togo","nl":"Togo","pl":"Togo","ro":"Togo","el":"Τόγκο","bg":"Того","sk":"Togo","sl":"Togo","fi":"Togo","hr":"Togo","hu":"Togo"} },
  { code: "TH", dial: "+66", names: {"en":"Thailand","fr":"Thaïlande","de":"Thailand","es":"Tailandia","it":"Thailandia","nl":"Thailand","pl":"Tajlandia","ro":"Thailanda","el":"Ταϊλάνδη","bg":"Тайланд","sk":"Thajsko","sl":"Tajska","fi":"Thaimaa","hr":"Tajland","hu":"Thaiföld"} },
  { code: "TJ", dial: "+992", names: {"en":"Tajikistan","fr":"Tadjikistan","de":"Tadschikistan","es":"Tayikistán","it":"Tagikistan","nl":"Tadzjikistan","pl":"Tadżykistan","ro":"Tadjikistan","el":"Τατζικιστάν","bg":"Таджикистан","sk":"Tadžikistan","sl":"Tadžikistan","fi":"Tadžikistan","hr":"Tadžikistan","hu":"Tádzsikisztán"} },
  { code: "TK", dial: "+690", names: {"en":"Tokelau","fr":"Tokelau","de":"Tokelau","es":"Tokelau","it":"Tokelau","nl":"Tokelau","pl":"Tokelau","ro":"Tokelau","el":"Τοκελάου","bg":"Токелау","sk":"Tokelau","sl":"Tokelau","fi":"Tokelau","hr":"Tokelau","hu":"Tokelau"} },
  { code: "TL", dial: "+670", names: {"en":"Timor-Leste","fr":"Timor oriental","de":"Timor-Leste","es":"Timor-Leste","it":"Timor Est","nl":"Oost-Timor","pl":"Timor Wschodni","ro":"Timor-Leste","el":"Τιμόρ-Λέστε","bg":"Тимор Лесте","sk":"Východný Timor","sl":"Timor-Leste","fi":"Itä-Timor","hr":"Timor-Leste","hu":"Kelet-Timor"} },
  { code: "TM", dial: "+993", names: {"en":"Turkmenistan","fr":"Turkménistan","de":"Turkmenistan","es":"Turkmenistán","it":"Turkmenistan","nl":"Turkmenistan","pl":"Turkmenistan","ro":"Turkmenistan","el":"Τουρκμενιστάν","bg":"Туркменистан","sk":"Turkménsko","sl":"Turkmenistan","fi":"Turkmenistan","hr":"Turkmenistan","hu":"Türkmenisztán"} },
  { code: "TN", dial: "+216", names: {"en":"Tunisia","fr":"Tunisie","de":"Tunesien","es":"Túnez","it":"Tunisia","nl":"Tunesië","pl":"Tunezja","ro":"Tunisia","el":"Τυνησία","bg":"Тунис","sk":"Tunisko","sl":"Tunizija","fi":"Tunisia","hr":"Tunis","hu":"Tunézia"} },
  { code: "TO", dial: "+676", names: {"en":"Tonga","fr":"Tonga","de":"Tonga","es":"Tonga","it":"Tonga","nl":"Tonga","pl":"Tonga","ro":"Tonga","el":"Τόνγκα","bg":"Тонга","sk":"Tonga","sl":"Tonga","fi":"Tonga","hr":"Tonga","hu":"Tonga"} },
  { code: "TR", dial: "+90", names: {"en":"Türkiye","fr":"Turquie","de":"Türkei","es":"Turquía","it":"Turchia","nl":"Turkije","pl":"Turcja","ro":"Turcia","el":"Τουρκία","bg":"Турция","sk":"Turecko","sl":"Turčija","fi":"Turkki","hr":"Turska","hu":"Törökország"} },
  { code: "TT", dial: "+1868", names: {"en":"Trinidad & Tobago","fr":"Trinité-et-Tobago","de":"Trinidad und Tobago","es":"Trinidad y Tobago","it":"Trinidad e Tobago","nl":"Trinidad en Tobago","pl":"Trynidad i Tobago","ro":"Trinidad și Tobago","el":"Τρινιντάντ και Τομπάγκο","bg":"Тринидад и Тобаго","sk":"Trinidad a Tobago","sl":"Trinidad in Tobago","fi":"Trinidad ja Tobago","hr":"Trinidad i Tobago","hu":"Trinidad és Tobago"} },
  { code: "TV", dial: "+688", names: {"en":"Tuvalu","fr":"Tuvalu","de":"Tuvalu","es":"Tuvalu","it":"Tuvalu","nl":"Tuvalu","pl":"Tuvalu","ro":"Tuvalu","el":"Τουβαλού","bg":"Тувалу","sk":"Tuvalu","sl":"Tuvalu","fi":"Tuvalu","hr":"Tuvalu","hu":"Tuvalu"} },
  { code: "TW", dial: "+886", names: {"en":"Taiwan","fr":"Taïwan","de":"Taiwan","es":"Taiwán","it":"Taiwan","nl":"Taiwan","pl":"Tajwan","ro":"Taiwan","el":"Ταϊβάν","bg":"Тайван","sk":"Taiwan","sl":"Tajvan","fi":"Taiwan","hr":"Tajvan","hu":"Tajvan"} },
  { code: "TZ", dial: "+255", names: {"en":"Tanzania","fr":"Tanzanie","de":"Tansania","es":"Tanzania","it":"Tanzania","nl":"Tanzania","pl":"Tanzania","ro":"Tanzania","el":"Τανζανία","bg":"Танзания","sk":"Tanzánia","sl":"Tanzanija","fi":"Tansania","hr":"Tanzanija","hu":"Tanzánia"} },
  { code: "UA", dial: "+380", names: {"en":"Ukraine","fr":"Ukraine","de":"Ukraine","es":"Ucrania","it":"Ucraina","nl":"Oekraïne","pl":"Ukraina","ro":"Ucraina","el":"Ουκρανία","bg":"Украйна","sk":"Ukrajina","sl":"Ukrajina","fi":"Ukraina","hr":"Ukrajina","hu":"Ukrajna"} },
  { code: "UG", dial: "+256", names: {"en":"Uganda","fr":"Ouganda","de":"Uganda","es":"Uganda","it":"Uganda","nl":"Oeganda","pl":"Uganda","ro":"Uganda","el":"Ουγκάντα","bg":"Уганда","sk":"Uganda","sl":"Uganda","fi":"Uganda","hr":"Uganda","hu":"Uganda"} },
  { code: "US", dial: "+1", names: {"en":"United States","fr":"États-Unis","de":"Vereinigte Staaten","es":"Estados Unidos","it":"Stati Uniti","nl":"Verenigde Staten","pl":"Stany Zjednoczone","ro":"Statele Unite ale Americii","el":"Ηνωμένες Πολιτείες","bg":"Съединени щати","sk":"Spojené štáty","sl":"Združene države Amerike","fi":"Yhdysvallat","hr":"Sjedinjene Američke Države","hu":"Egyesült Államok"} },
  { code: "UY", dial: "+598", names: {"en":"Uruguay","fr":"Uruguay","de":"Uruguay","es":"Uruguay","it":"Uruguay","nl":"Uruguay","pl":"Urugwaj","ro":"Uruguay","el":"Ουρουγουάη","bg":"Уругвай","sk":"Uruguaj","sl":"Urugvaj","fi":"Uruguay","hr":"Urugvaj","hu":"Uruguay"} },
  { code: "UZ", dial: "+998", names: {"en":"Uzbekistan","fr":"Ouzbékistan","de":"Usbekistan","es":"Uzbekistán","it":"Uzbekistan","nl":"Oezbekistan","pl":"Uzbekistan","ro":"Uzbekistan","el":"Ουζμπεκιστάν","bg":"Узбекистан","sk":"Uzbekistan","sl":"Uzbekistan","fi":"Uzbekistan","hr":"Uzbekistan","hu":"Üzbegisztán"} },
  { code: "VA", dial: "+39", names: {"en":"Vatican City","fr":"État de la Cité du Vatican","de":"Vatikanstadt","es":"Ciudad del Vaticano","it":"Città del Vaticano","nl":"Vaticaanstad","pl":"Watykan","ro":"Statul Cetății Vaticanului","el":"Βατικανό","bg":"Ватикан","sk":"Vatikán","sl":"Vatikan","fi":"Vatikaani","hr":"Vatikan","hu":"Vatikán"} },
  { code: "VC", dial: "+1784", names: {"en":"St. Vincent & Grenadines","fr":"Saint-Vincent-et-les Grenadines","de":"St. Vincent und die Grenadinen","es":"San Vicente y las Granadinas","it":"Saint Vincent e Grenadine","nl":"Saint Vincent en de Grenadines","pl":"Saint Vincent i Grenadyny","ro":"Saint Vincent și Grenadinele","el":"Άγιος Βικέντιος και Γρεναδίνες","bg":"Сейнт Винсънт и Гренадини","sk":"Svätý Vincent a Grenadíny","sl":"Saint Vincent in Grenadine","fi":"Saint Vincent ja Grenadiinit","hr":"Sveti Vincent i Grenadini","hu":"Saint Vincent és a Grenadine-szigetek"} },
  { code: "VE", dial: "+58", names: {"en":"Venezuela","fr":"Venezuela","de":"Venezuela","es":"Venezuela","it":"Venezuela","nl":"Venezuela","pl":"Wenezuela","ro":"Venezuela","el":"Βενεζουέλα","bg":"Венецуела","sk":"Venezuela","sl":"Venezuela","fi":"Venezuela","hr":"Venezuela","hu":"Venezuela"} },
  { code: "VG", dial: "+1284", names: {"en":"British Virgin Islands","fr":"Îles Vierges britanniques","de":"Britische Jungferninseln","es":"Islas Vírgenes Británicas","it":"Isole Vergini Britanniche","nl":"Britse Maagdeneilanden","pl":"Brytyjskie Wyspy Dziewicze","ro":"Insulele Virgine Britanice","el":"Βρετανικές Παρθένες Νήσοι","bg":"Британски Вирджински острови","sk":"Britské Panenské ostrovy","sl":"Britanski Deviški otoki","fi":"Brittiläiset Neitsytsaaret","hr":"Britanski Djevičanski Otoci","hu":"Brit Virgin-szigetek"} },
  { code: "VI", dial: "+1340", names: {"en":"U.S. Virgin Islands","fr":"Îles Vierges des États-Unis","de":"Amerikanische Jungferninseln","es":"Islas Vírgenes de EE. UU.","it":"Isole Vergini Americane","nl":"Amerikaanse Maagdeneilanden","pl":"Wyspy Dziewicze Stanów Zjednoczonych","ro":"Insulele Virgine Americane","el":"Αμερικανικές Παρθένες Νήσοι","bg":"Американски Вирджински острови","sk":"Americké Panenské ostrovy","sl":"Ameriški Deviški otoki","fi":"Yhdysvaltain Neitsytsaaret","hr":"Američki Djevičanski Otoci","hu":"Amerikai Virgin-szigetek"} },
  { code: "VN", dial: "+84", names: {"en":"Vietnam","fr":"Viêt Nam","de":"Vietnam","es":"Vietnam","it":"Vietnam","nl":"Vietnam","pl":"Wietnam","ro":"Vietnam","el":"Βιετνάμ","bg":"Виетнам","sk":"Vietnam","sl":"Vietnam","fi":"Vietnam","hr":"Vijetnam","hu":"Vietnám"} },
  { code: "VU", dial: "+678", names: {"en":"Vanuatu","fr":"Vanuatu","de":"Vanuatu","es":"Vanuatu","it":"Vanuatu","nl":"Vanuatu","pl":"Vanuatu","ro":"Vanuatu","el":"Βανουάτου","bg":"Вануату","sk":"Vanuatu","sl":"Vanuatu","fi":"Vanuatu","hr":"Vanuatu","hu":"Vanuatu"} },
  { code: "WF", dial: "+681", names: {"en":"Wallis & Futuna","fr":"Wallis-et-Futuna","de":"Wallis und Futuna","es":"Wallis y Futuna","it":"Wallis e Futuna","nl":"Wallis en Futuna","pl":"Wallis i Futuna","ro":"Wallis și Futuna","el":"Γουάλις και Φουτούνα","bg":"Уолис и Футуна","sk":"Wallis a Futuna","sl":"Wallis in Futuna","fi":"Wallis ja Futuna","hr":"Wallis i Futuna","hu":"Wallis és Futuna"} },
  { code: "WS", dial: "+685", names: {"en":"Samoa","fr":"Samoa","de":"Samoa","es":"Samoa","it":"Samoa","nl":"Samoa","pl":"Samoa","ro":"Samoa","el":"Σαμόα","bg":"Самоа","sk":"Samoa","sl":"Samoa","fi":"Samoa","hr":"Samoa","hu":"Szamoa"} },
  { code: "XK", dial: "+383", names: {"en":"Kosovo","fr":"Kosovo","de":"Kosovo","es":"Kosovo","it":"Kosovo","nl":"Kosovo","pl":"Kosowo","ro":"Kosovo","el":"Κοσσυφοπέδιο","bg":"Косово","sk":"Kosovo","sl":"Kosovo","fi":"Kosovo","hr":"Kosovo","hu":"Koszovó"} },
  { code: "YE", dial: "+967", names: {"en":"Yemen","fr":"Yémen","de":"Jemen","es":"Yemen","it":"Yemen","nl":"Jemen","pl":"Jemen","ro":"Yemen","el":"Υεμένη","bg":"Йемен","sk":"Jemen","sl":"Jemen","fi":"Jemen","hr":"Jemen","hu":"Jemen"} },
  { code: "YT", dial: "+262", names: {"en":"Mayotte","fr":"Mayotte","de":"Mayotte","es":"Mayotte","it":"Mayotte","nl":"Mayotte","pl":"Majotta","ro":"Mayotte","el":"Μαγιότ","bg":"Майот","sk":"Mayotte","sl":"Mayotte","fi":"Mayotte","hr":"Mayotte","hu":"Mayotte"} },
  { code: "ZA", dial: "+27", names: {"en":"South Africa","fr":"Afrique du Sud","de":"Südafrika","es":"Sudáfrica","it":"Sudafrica","nl":"Zuid-Afrika","pl":"Republika Południowej Afryki","ro":"Africa de Sud","el":"Νότια Αφρική","bg":"Южна Африка","sk":"Južná Afrika","sl":"Južnoafriška republika","fi":"Etelä-Afrikka","hr":"Južnoafrička Republika","hu":"Dél-afrikai Köztársaság"} },
  { code: "ZM", dial: "+260", names: {"en":"Zambia","fr":"Zambie","de":"Sambia","es":"Zambia","it":"Zambia","nl":"Zambia","pl":"Zambia","ro":"Zambia","el":"Ζάμπια","bg":"Замбия","sk":"Zambia","sl":"Zambija","fi":"Sambia","hr":"Zambija","hu":"Zambia"} },
  { code: "ZW", dial: "+263", names: {"en":"Zimbabwe","fr":"Zimbabwe","de":"Simbabwe","es":"Zimbabue","it":"Zimbabwe","nl":"Zimbabwe","pl":"Zimbabwe","ro":"Zimbabwe","el":"Ζιμπάμπουε","bg":"Зимбабве","sk":"Zimbabwe","sl":"Zimbabve","fi":"Zimbabwe","hr":"Zimbabve","hu":"Zimbabwe"} },
];

const BY_CODE = new Map(COUNTRIES.map((c) => [c.code, c]));

/** SEPA / EEA zone — used for banking coherence checks. */
export const SEPA_COUNTRIES = new Set([
  "AT","BE","BG","CH","CY","CZ","DE","DK","EE","ES","FI","FR","GB","GI","GR","HR","HU","IE",
  "IS","IT","LI","LT","LU","LV","MC","MT","NL","NO","PL","PT","RO","SE","SI","SK","SM","VA",
]);

export function countryByCode(code: string | null | undefined): Country | undefined {
  if (!code) return undefined;
  return BY_CODE.get(code.trim().toUpperCase());
}

export function countryName(code: string | null | undefined, locale = "en"): string {
  const c = countryByCode(code);
  if (!c) return code ?? "";
  const lang = (locale || "en").split("-")[0]!;
  return c.names[lang] ?? c.names.en ?? c.code;
}

/** Emoji-free flag asset: crisp SVG served by the flag CDN. */
export function flagUrl(code: string): string {
  return `https://flagcdn.com/${code.toLowerCase()}.svg`;
}

const strip = (s: string) =>
  s.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();

/** Instant, accent-insensitive search across every localised name + dial code. */
export function searchCountries(query: string, locale = "en", limit = 300): Country[] {
  const q = strip(query.trim());
  const lang = (locale || "en").split("-")[0]!;
  const sorted = [...COUNTRIES].sort((a, b) =>
    countryName(a.code, lang).localeCompare(countryName(b.code, lang), lang),
  );
  if (!q) return sorted.slice(0, limit);
  const scored: Array<{ c: Country; score: number }> = [];
  for (const c of sorted) {
    const local = strip(countryName(c.code, lang));
    const english = strip(c.names.en ?? "");
    const dial = c.dial.replace("+", "");
    let score = -1;
    if (local.startsWith(q) || english.startsWith(q)) score = 0;
    else if (strip(c.code) === q) score = 1;
    else if (dial.startsWith(q.replace("+", "")) && /^\+?\d+$/.test(query.trim())) score = 2;
    else if (local.includes(q) || english.includes(q)) score = 3;
    if (score >= 0) scored.push({ c, score });
  }
  scored.sort((a, b) => a.score - b.score);
  return scored.slice(0, limit).map((s) => s.c);
}

/** Best-effort country guess from a free-text country label (address results). */
export function resolveCountryCode(input: string | null | undefined): string | null {
  if (!input) return null;
  const raw = input.trim();
  if (raw.length === 2 && BY_CODE.has(raw.toUpperCase())) return raw.toUpperCase();
  const q = strip(raw);
  for (const c of COUNTRIES) {
    for (const name of Object.values(c.names)) {
      if (strip(name) === q) return c.code;
    }
  }
  return null;
}
