/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffInviteRouteImport } from './routes/staff-invite'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRepaymentRouteImport } from './routes/legal.repayment'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalMentionsRouteImport } from './routes/legal.mentions'
import { Route as LegalLoanTermsRouteImport } from './routes/legal.loan-terms'
import { Route as LegalFinancialPrivacyRouteImport } from './routes/legal.financial-privacy'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalAmlKycRouteImport } from './routes/legal.aml-kyc'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminVerifyRouteImport } from './routes/admin.verify'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminKycRequestsRouteImport } from './routes/admin.kyc-requests'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as LangSolutionsRouteImport } from './routes/$lang.solutions'
import { Route as LangSimulationRouteImport } from './routes/$lang.simulation'
import { Route as LangHomeRouteImport } from './routes/$lang.home'
import { Route as LangContactRouteImport } from './routes/$lang.contact'
import { Route as LangApplyRouteImport } from './routes/$lang.apply'
import { Route as LangAboutRouteImport } from './routes/$lang.about'
import { Route as LangSplatRouteImport } from './routes/$lang.$'
import { Route as AdminApplicationsIndexRouteImport } from './routes/admin.applications.index'
import { Route as SecureApplicationTokenRouteImport } from './routes/secure.application.$token'
import { Route as ApiPublicRepaymentRemindersRouteImport } from './routes/api/public/repayment-reminders'
import { Route as ApiPublicGuaranteeRemindersRouteImport } from './routes/api/public/guarantee-reminders'
import { Route as AdminApplicationsApplicationIdRouteImport } from './routes/admin.applications.$applicationId'
import { Route as LangLegalTermsRouteImport } from './routes/$lang.legal.terms'
import { Route as LangLegalRepaymentRouteImport } from './routes/$lang.legal.repayment'
import { Route as LangLegalPrivacyRouteImport } from './routes/$lang.legal.privacy'
import { Route as LangLegalMentionsRouteImport } from './routes/$lang.legal.mentions'
import { Route as LangLegalLoanTermsRouteImport } from './routes/$lang.legal.loan-terms'
import { Route as LangLegalFinancialPrivacyRouteImport } from './routes/$lang.legal.financial-privacy'
import { Route as LangLegalCookiesRouteImport } from './routes/$lang.legal.cookies'
import { Route as LangLegalAmlKycRouteImport } from './routes/$lang.legal.aml-kyc'
import { Route as LangSecureApplicationTokenIndexRouteImport } from './routes/$lang.secure.application.$token.index'
import { Route as LangSecureApplicationTokenPaymentRouteImport } from './routes/$lang.secure.application.$token.payment'
import { Route as LangSecureApplicationTokenContractRouteImport } from './routes/$lang.secure.application.$token.contract'

const StaffInviteRoute = StaffInviteRouteImport.update({
  id: '/staff-invite',
  path: '/staff-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRepaymentRoute = LegalRepaymentRouteImport.update({
  id: '/legal/repayment',
  path: '/legal/repayment',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalMentionsRoute = LegalMentionsRouteImport.update({
  id: '/legal/mentions',
  path: '/legal/mentions',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalLoanTermsRoute = LegalLoanTermsRouteImport.update({
  id: '/legal/loan-terms',
  path: '/legal/loan-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalFinancialPrivacyRoute = LegalFinancialPrivacyRouteImport.update({
  id: '/legal/financial-privacy',
  path: '/legal/financial-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAmlKycRoute = LegalAmlKycRouteImport.update({
  id: '/legal/aml-kyc',
  path: '/legal/aml-kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AdminVerifyRoute = AdminVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRequestsRoute = AdminKycRequestsRouteImport.update({
  id: '/kyc-requests',
  path: '/kyc-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const LangSolutionsRoute = LangSolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => LangRoute,
} as any)
const LangSimulationRoute = LangSimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => LangRoute,
} as any)
const LangHomeRoute = LangHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LangRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangApplyRoute = LangApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)
const LangSplatRoute = LangSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LangRoute,
} as any)
const AdminApplicationsIndexRoute = AdminApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => AdminRoute,
} as any)
const SecureApplicationTokenRoute = SecureApplicationTokenRouteImport.update({
  id: '/secure/application/$token',
  path: '/secure/application/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRepaymentRemindersRoute =
  ApiPublicRepaymentRemindersRouteImport.update({
    id: '/api/public/repayment-reminders',
    path: '/api/public/repayment-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGuaranteeRemindersRoute =
  ApiPublicGuaranteeRemindersRouteImport.update({
    id: '/api/public/guarantee-reminders',
    path: '/api/public/guarantee-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminApplicationsApplicationIdRoute =
  AdminApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => AdminRoute,
  } as any)
const LangLegalTermsRoute = LangLegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => LangRoute,
} as any)
const LangLegalRepaymentRoute = LangLegalRepaymentRouteImport.update({
  id: '/legal/repayment',
  path: '/legal/repayment',
  getParentRoute: () => LangRoute,
} as any)
const LangLegalPrivacyRoute = LangLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => LangRoute,
} as any)
const LangLegalMentionsRoute = LangLegalMentionsRouteImport.update({
  id: '/legal/mentions',
  path: '/legal/mentions',
  getParentRoute: () => LangRoute,
} as any)
const LangLegalLoanTermsRoute = LangLegalLoanTermsRouteImport.update({
  id: '/legal/loan-terms',
  path: '/legal/loan-terms',
  getParentRoute: () => LangRoute,
} as any)
const LangLegalFinancialPrivacyRoute =
  LangLegalFinancialPrivacyRouteImport.update({
    id: '/legal/financial-privacy',
    path: '/legal/financial-privacy',
    getParentRoute: () => LangRoute,
  } as any)
const LangLegalCookiesRoute = LangLegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => LangRoute,
} as any)
const LangLegalAmlKycRoute = LangLegalAmlKycRouteImport.update({
  id: '/legal/aml-kyc',
  path: '/legal/aml-kyc',
  getParentRoute: () => LangRoute,
} as any)
const LangSecureApplicationTokenIndexRoute =
  LangSecureApplicationTokenIndexRouteImport.update({
    id: '/secure/application/$token/',
    path: '/secure/application/$token/',
    getParentRoute: () => LangRoute,
  } as any)
const LangSecureApplicationTokenPaymentRoute =
  LangSecureApplicationTokenPaymentRouteImport.update({
    id: '/secure/application/$token/payment',
    path: '/secure/application/$token/payment',
    getParentRoute: () => LangRoute,
  } as any)
const LangSecureApplicationTokenContractRoute =
  LangSecureApplicationTokenContractRouteImport.update({
    id: '/secure/application/$token/contract',
    path: '/secure/application/$token/contract',
    getParentRoute: () => LangRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulation': typeof SimulationRoute
  '/solutions': typeof SolutionsRoute
  '/staff-invite': typeof StaffInviteRoute
  '/$lang/$': typeof LangSplatRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/apply': typeof LangApplyRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/home': typeof LangHomeRoute
  '/$lang/simulation': typeof LangSimulationRoute
  '/$lang/solutions': typeof LangSolutionsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/kyc-requests': typeof AdminKycRequestsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/legal/aml-kyc': typeof LegalAmlKycRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/financial-privacy': typeof LegalFinancialPrivacyRoute
  '/legal/loan-terms': typeof LegalLoanTermsRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/repayment': typeof LegalRepaymentRoute
  '/legal/terms': typeof LegalTermsRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$lang/legal/aml-kyc': typeof LangLegalAmlKycRoute
  '/$lang/legal/cookies': typeof LangLegalCookiesRoute
  '/$lang/legal/financial-privacy': typeof LangLegalFinancialPrivacyRoute
  '/$lang/legal/loan-terms': typeof LangLegalLoanTermsRoute
  '/$lang/legal/mentions': typeof LangLegalMentionsRoute
  '/$lang/legal/privacy': typeof LangLegalPrivacyRoute
  '/$lang/legal/repayment': typeof LangLegalRepaymentRoute
  '/$lang/legal/terms': typeof LangLegalTermsRoute
  '/admin/applications/$applicationId': typeof AdminApplicationsApplicationIdRoute
  '/api/public/guarantee-reminders': typeof ApiPublicGuaranteeRemindersRoute
  '/api/public/repayment-reminders': typeof ApiPublicRepaymentRemindersRoute
  '/secure/application/$token': typeof SecureApplicationTokenRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/$lang/secure/application/$token/contract': typeof LangSecureApplicationTokenContractRoute
  '/$lang/secure/application/$token/payment': typeof LangSecureApplicationTokenPaymentRoute
  '/$lang/secure/application/$token/': typeof LangSecureApplicationTokenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulation': typeof SimulationRoute
  '/solutions': typeof SolutionsRoute
  '/staff-invite': typeof StaffInviteRoute
  '/$lang/$': typeof LangSplatRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/apply': typeof LangApplyRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/home': typeof LangHomeRoute
  '/$lang/simulation': typeof LangSimulationRoute
  '/$lang/solutions': typeof LangSolutionsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/kyc-requests': typeof AdminKycRequestsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/legal/aml-kyc': typeof LegalAmlKycRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/financial-privacy': typeof LegalFinancialPrivacyRoute
  '/legal/loan-terms': typeof LegalLoanTermsRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/repayment': typeof LegalRepaymentRoute
  '/legal/terms': typeof LegalTermsRoute
  '/$lang': typeof LangIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$lang/legal/aml-kyc': typeof LangLegalAmlKycRoute
  '/$lang/legal/cookies': typeof LangLegalCookiesRoute
  '/$lang/legal/financial-privacy': typeof LangLegalFinancialPrivacyRoute
  '/$lang/legal/loan-terms': typeof LangLegalLoanTermsRoute
  '/$lang/legal/mentions': typeof LangLegalMentionsRoute
  '/$lang/legal/privacy': typeof LangLegalPrivacyRoute
  '/$lang/legal/repayment': typeof LangLegalRepaymentRoute
  '/$lang/legal/terms': typeof LangLegalTermsRoute
  '/admin/applications/$applicationId': typeof AdminApplicationsApplicationIdRoute
  '/api/public/guarantee-reminders': typeof ApiPublicGuaranteeRemindersRoute
  '/api/public/repayment-reminders': typeof ApiPublicRepaymentRemindersRoute
  '/secure/application/$token': typeof SecureApplicationTokenRoute
  '/admin/applications': typeof AdminApplicationsIndexRoute
  '/$lang/secure/application/$token/contract': typeof LangSecureApplicationTokenContractRoute
  '/$lang/secure/application/$token/payment': typeof LangSecureApplicationTokenPaymentRoute
  '/$lang/secure/application/$token': typeof LangSecureApplicationTokenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulation': typeof SimulationRoute
  '/solutions': typeof SolutionsRoute
  '/staff-invite': typeof StaffInviteRoute
  '/$lang/$': typeof LangSplatRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/apply': typeof LangApplyRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/home': typeof LangHomeRoute
  '/$lang/simulation': typeof LangSimulationRoute
  '/$lang/solutions': typeof LangSolutionsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/kyc-requests': typeof AdminKycRequestsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/legal/aml-kyc': typeof LegalAmlKycRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/financial-privacy': typeof LegalFinancialPrivacyRoute
  '/legal/loan-terms': typeof LegalLoanTermsRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/repayment': typeof LegalRepaymentRoute
  '/legal/terms': typeof LegalTermsRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$lang/legal/aml-kyc': typeof LangLegalAmlKycRoute
  '/$lang/legal/cookies': typeof LangLegalCookiesRoute
  '/$lang/legal/financial-privacy': typeof LangLegalFinancialPrivacyRoute
  '/$lang/legal/loan-terms': typeof LangLegalLoanTermsRoute
  '/$lang/legal/mentions': typeof LangLegalMentionsRoute
  '/$lang/legal/privacy': typeof LangLegalPrivacyRoute
  '/$lang/legal/repayment': typeof LangLegalRepaymentRoute
  '/$lang/legal/terms': typeof LangLegalTermsRoute
  '/admin/applications/$applicationId': typeof AdminApplicationsApplicationIdRoute
  '/api/public/guarantee-reminders': typeof ApiPublicGuaranteeRemindersRoute
  '/api/public/repayment-reminders': typeof ApiPublicRepaymentRemindersRoute
  '/secure/application/$token': typeof SecureApplicationTokenRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/$lang/secure/application/$token/contract': typeof LangSecureApplicationTokenContractRoute
  '/$lang/secure/application/$token/payment': typeof LangSecureApplicationTokenPaymentRoute
  '/$lang/secure/application/$token/': typeof LangSecureApplicationTokenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/about'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/simulation'
    | '/solutions'
    | '/staff-invite'
    | '/$lang/$'
    | '/$lang/about'
    | '/$lang/apply'
    | '/$lang/contact'
    | '/$lang/home'
    | '/$lang/simulation'
    | '/$lang/solutions'
    | '/admin/kyc'
    | '/admin/kyc-requests'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/products'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/verify'
    | '/auth/callback'
    | '/legal/aml-kyc'
    | '/legal/cookies'
    | '/legal/financial-privacy'
    | '/legal/loan-terms'
    | '/legal/mentions'
    | '/legal/privacy'
    | '/legal/repayment'
    | '/legal/terms'
    | '/$lang/'
    | '/admin/'
    | '/$lang/legal/aml-kyc'
    | '/$lang/legal/cookies'
    | '/$lang/legal/financial-privacy'
    | '/$lang/legal/loan-terms'
    | '/$lang/legal/mentions'
    | '/$lang/legal/privacy'
    | '/$lang/legal/repayment'
    | '/$lang/legal/terms'
    | '/admin/applications/$applicationId'
    | '/api/public/guarantee-reminders'
    | '/api/public/repayment-reminders'
    | '/secure/application/$token'
    | '/admin/applications/'
    | '/$lang/secure/application/$token/contract'
    | '/$lang/secure/application/$token/payment'
    | '/$lang/secure/application/$token/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/simulation'
    | '/solutions'
    | '/staff-invite'
    | '/$lang/$'
    | '/$lang/about'
    | '/$lang/apply'
    | '/$lang/contact'
    | '/$lang/home'
    | '/$lang/simulation'
    | '/$lang/solutions'
    | '/admin/kyc'
    | '/admin/kyc-requests'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/products'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/verify'
    | '/auth/callback'
    | '/legal/aml-kyc'
    | '/legal/cookies'
    | '/legal/financial-privacy'
    | '/legal/loan-terms'
    | '/legal/mentions'
    | '/legal/privacy'
    | '/legal/repayment'
    | '/legal/terms'
    | '/$lang'
    | '/admin'
    | '/$lang/legal/aml-kyc'
    | '/$lang/legal/cookies'
    | '/$lang/legal/financial-privacy'
    | '/$lang/legal/loan-terms'
    | '/$lang/legal/mentions'
    | '/$lang/legal/privacy'
    | '/$lang/legal/repayment'
    | '/$lang/legal/terms'
    | '/admin/applications/$applicationId'
    | '/api/public/guarantee-reminders'
    | '/api/public/repayment-reminders'
    | '/secure/application/$token'
    | '/admin/applications'
    | '/$lang/secure/application/$token/contract'
    | '/$lang/secure/application/$token/payment'
    | '/$lang/secure/application/$token'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/about'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/simulation'
    | '/solutions'
    | '/staff-invite'
    | '/$lang/$'
    | '/$lang/about'
    | '/$lang/apply'
    | '/$lang/contact'
    | '/$lang/home'
    | '/$lang/simulation'
    | '/$lang/solutions'
    | '/admin/kyc'
    | '/admin/kyc-requests'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/products'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/verify'
    | '/auth/callback'
    | '/legal/aml-kyc'
    | '/legal/cookies'
    | '/legal/financial-privacy'
    | '/legal/loan-terms'
    | '/legal/mentions'
    | '/legal/privacy'
    | '/legal/repayment'
    | '/legal/terms'
    | '/$lang/'
    | '/admin/'
    | '/$lang/legal/aml-kyc'
    | '/$lang/legal/cookies'
    | '/$lang/legal/financial-privacy'
    | '/$lang/legal/loan-terms'
    | '/$lang/legal/mentions'
    | '/$lang/legal/privacy'
    | '/$lang/legal/repayment'
    | '/$lang/legal/terms'
    | '/admin/applications/$applicationId'
    | '/api/public/guarantee-reminders'
    | '/api/public/repayment-reminders'
    | '/secure/application/$token'
    | '/admin/applications/'
    | '/$lang/secure/application/$token/contract'
    | '/$lang/secure/application/$token/payment'
    | '/$lang/secure/application/$token/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SimulationRoute: typeof SimulationRoute
  SolutionsRoute: typeof SolutionsRoute
  StaffInviteRoute: typeof StaffInviteRoute
  LegalAmlKycRoute: typeof LegalAmlKycRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalFinancialPrivacyRoute: typeof LegalFinancialPrivacyRoute
  LegalLoanTermsRoute: typeof LegalLoanTermsRoute
  LegalMentionsRoute: typeof LegalMentionsRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRepaymentRoute: typeof LegalRepaymentRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ApiPublicGuaranteeRemindersRoute: typeof ApiPublicGuaranteeRemindersRoute
  ApiPublicRepaymentRemindersRoute: typeof ApiPublicRepaymentRemindersRoute
  SecureApplicationTokenRoute: typeof SecureApplicationTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff-invite': {
      id: '/staff-invite'
      path: '/staff-invite'
      fullPath: '/staff-invite'
      preLoaderRoute: typeof StaffInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/repayment': {
      id: '/legal/repayment'
      path: '/legal/repayment'
      fullPath: '/legal/repayment'
      preLoaderRoute: typeof LegalRepaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/mentions': {
      id: '/legal/mentions'
      path: '/legal/mentions'
      fullPath: '/legal/mentions'
      preLoaderRoute: typeof LegalMentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/loan-terms': {
      id: '/legal/loan-terms'
      path: '/legal/loan-terms'
      fullPath: '/legal/loan-terms'
      preLoaderRoute: typeof LegalLoanTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/financial-privacy': {
      id: '/legal/financial-privacy'
      path: '/legal/financial-privacy'
      fullPath: '/legal/financial-privacy'
      preLoaderRoute: typeof LegalFinancialPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/aml-kyc': {
      id: '/legal/aml-kyc'
      path: '/legal/aml-kyc'
      fullPath: '/legal/aml-kyc'
      preLoaderRoute: typeof LegalAmlKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/verify': {
      id: '/admin/verify'
      path: '/verify'
      fullPath: '/admin/verify'
      preLoaderRoute: typeof AdminVerifyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc-requests': {
      id: '/admin/kyc-requests'
      path: '/kyc-requests'
      fullPath: '/admin/kyc-requests'
      preLoaderRoute: typeof AdminKycRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$lang/solutions': {
      id: '/$lang/solutions'
      path: '/solutions'
      fullPath: '/$lang/solutions'
      preLoaderRoute: typeof LangSolutionsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/simulation': {
      id: '/$lang/simulation'
      path: '/simulation'
      fullPath: '/$lang/simulation'
      preLoaderRoute: typeof LangSimulationRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/home': {
      id: '/$lang/home'
      path: '/home'
      fullPath: '/$lang/home'
      preLoaderRoute: typeof LangHomeRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/apply': {
      id: '/$lang/apply'
      path: '/apply'
      fullPath: '/$lang/apply'
      preLoaderRoute: typeof LangApplyRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/$': {
      id: '/$lang/$'
      path: '/$'
      fullPath: '/$lang/$'
      preLoaderRoute: typeof LangSplatRouteImport
      parentRoute: typeof LangRoute
    }
    '/admin/applications/': {
      id: '/admin/applications/'
      path: '/applications'
      fullPath: '/admin/applications/'
      preLoaderRoute: typeof AdminApplicationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/secure/application/$token': {
      id: '/secure/application/$token'
      path: '/secure/application/$token'
      fullPath: '/secure/application/$token'
      preLoaderRoute: typeof SecureApplicationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/repayment-reminders': {
      id: '/api/public/repayment-reminders'
      path: '/api/public/repayment-reminders'
      fullPath: '/api/public/repayment-reminders'
      preLoaderRoute: typeof ApiPublicRepaymentRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/guarantee-reminders': {
      id: '/api/public/guarantee-reminders'
      path: '/api/public/guarantee-reminders'
      fullPath: '/api/public/guarantee-reminders'
      preLoaderRoute: typeof ApiPublicGuaranteeRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications/$applicationId': {
      id: '/admin/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/admin/applications/$applicationId'
      preLoaderRoute: typeof AdminApplicationsApplicationIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$lang/legal/terms': {
      id: '/$lang/legal/terms'
      path: '/legal/terms'
      fullPath: '/$lang/legal/terms'
      preLoaderRoute: typeof LangLegalTermsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/legal/repayment': {
      id: '/$lang/legal/repayment'
      path: '/legal/repayment'
      fullPath: '/$lang/legal/repayment'
      preLoaderRoute: typeof LangLegalRepaymentRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/legal/privacy': {
      id: '/$lang/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/$lang/legal/privacy'
      preLoaderRoute: typeof LangLegalPrivacyRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/legal/mentions': {
      id: '/$lang/legal/mentions'
      path: '/legal/mentions'
      fullPath: '/$lang/legal/mentions'
      preLoaderRoute: typeof LangLegalMentionsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/legal/loan-terms': {
      id: '/$lang/legal/loan-terms'
      path: '/legal/loan-terms'
      fullPath: '/$lang/legal/loan-terms'
      preLoaderRoute: typeof LangLegalLoanTermsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/legal/financial-privacy': {
      id: '/$lang/legal/financial-privacy'
      path: '/legal/financial-privacy'
      fullPath: '/$lang/legal/financial-privacy'
      preLoaderRoute: typeof LangLegalFinancialPrivacyRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/legal/cookies': {
      id: '/$lang/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/$lang/legal/cookies'
      preLoaderRoute: typeof LangLegalCookiesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/legal/aml-kyc': {
      id: '/$lang/legal/aml-kyc'
      path: '/legal/aml-kyc'
      fullPath: '/$lang/legal/aml-kyc'
      preLoaderRoute: typeof LangLegalAmlKycRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/secure/application/$token/': {
      id: '/$lang/secure/application/$token/'
      path: '/secure/application/$token'
      fullPath: '/$lang/secure/application/$token/'
      preLoaderRoute: typeof LangSecureApplicationTokenIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/secure/application/$token/payment': {
      id: '/$lang/secure/application/$token/payment'
      path: '/secure/application/$token/payment'
      fullPath: '/$lang/secure/application/$token/payment'
      preLoaderRoute: typeof LangSecureApplicationTokenPaymentRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/secure/application/$token/contract': {
      id: '/$lang/secure/application/$token/contract'
      path: '/secure/application/$token/contract'
      fullPath: '/$lang/secure/application/$token/contract'
      preLoaderRoute: typeof LangSecureApplicationTokenContractRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangSplatRoute: typeof LangSplatRoute
  LangAboutRoute: typeof LangAboutRoute
  LangApplyRoute: typeof LangApplyRoute
  LangContactRoute: typeof LangContactRoute
  LangHomeRoute: typeof LangHomeRoute
  LangSimulationRoute: typeof LangSimulationRoute
  LangSolutionsRoute: typeof LangSolutionsRoute
  LangIndexRoute: typeof LangIndexRoute
  LangLegalAmlKycRoute: typeof LangLegalAmlKycRoute
  LangLegalCookiesRoute: typeof LangLegalCookiesRoute
  LangLegalFinancialPrivacyRoute: typeof LangLegalFinancialPrivacyRoute
  LangLegalLoanTermsRoute: typeof LangLegalLoanTermsRoute
  LangLegalMentionsRoute: typeof LangLegalMentionsRoute
  LangLegalPrivacyRoute: typeof LangLegalPrivacyRoute
  LangLegalRepaymentRoute: typeof LangLegalRepaymentRoute
  LangLegalTermsRoute: typeof LangLegalTermsRoute
  LangSecureApplicationTokenContractRoute: typeof LangSecureApplicationTokenContractRoute
  LangSecureApplicationTokenPaymentRoute: typeof LangSecureApplicationTokenPaymentRoute
  LangSecureApplicationTokenIndexRoute: typeof LangSecureApplicationTokenIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangSplatRoute: LangSplatRoute,
  LangAboutRoute: LangAboutRoute,
  LangApplyRoute: LangApplyRoute,
  LangContactRoute: LangContactRoute,
  LangHomeRoute: LangHomeRoute,
  LangSimulationRoute: LangSimulationRoute,
  LangSolutionsRoute: LangSolutionsRoute,
  LangIndexRoute: LangIndexRoute,
  LangLegalAmlKycRoute: LangLegalAmlKycRoute,
  LangLegalCookiesRoute: LangLegalCookiesRoute,
  LangLegalFinancialPrivacyRoute: LangLegalFinancialPrivacyRoute,
  LangLegalLoanTermsRoute: LangLegalLoanTermsRoute,
  LangLegalMentionsRoute: LangLegalMentionsRoute,
  LangLegalPrivacyRoute: LangLegalPrivacyRoute,
  LangLegalRepaymentRoute: LangLegalRepaymentRoute,
  LangLegalTermsRoute: LangLegalTermsRoute,
  LangSecureApplicationTokenContractRoute:
    LangSecureApplicationTokenContractRoute,
  LangSecureApplicationTokenPaymentRoute:
    LangSecureApplicationTokenPaymentRoute,
  LangSecureApplicationTokenIndexRoute: LangSecureApplicationTokenIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

interface AdminRouteChildren {
  AdminKycRoute: typeof AdminKycRoute
  AdminKycRequestsRoute: typeof AdminKycRequestsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminVerifyRoute: typeof AdminVerifyRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminApplicationsApplicationIdRoute: typeof AdminApplicationsApplicationIdRoute
  AdminApplicationsIndexRoute: typeof AdminApplicationsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminKycRoute: AdminKycRoute,
  AdminKycRequestsRoute: AdminKycRequestsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminVerifyRoute: AdminVerifyRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminApplicationsApplicationIdRoute: AdminApplicationsApplicationIdRoute,
  AdminApplicationsIndexRoute: AdminApplicationsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplyRoute: ApplyRoute,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SimulationRoute: SimulationRoute,
  SolutionsRoute: SolutionsRoute,
  StaffInviteRoute: StaffInviteRoute,
  LegalAmlKycRoute: LegalAmlKycRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalFinancialPrivacyRoute: LegalFinancialPrivacyRoute,
  LegalLoanTermsRoute: LegalLoanTermsRoute,
  LegalMentionsRoute: LegalMentionsRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRepaymentRoute: LegalRepaymentRoute,
  LegalTermsRoute: LegalTermsRoute,
  ApiPublicGuaranteeRemindersRoute: ApiPublicGuaranteeRemindersRoute,
  ApiPublicRepaymentRemindersRoute: ApiPublicRepaymentRemindersRoute,
  SecureApplicationTokenRoute: SecureApplicationTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
