/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffInviteRouteImport } from './routes/staff-invite'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRepaymentRouteImport } from './routes/legal.repayment'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalMentionsRouteImport } from './routes/legal.mentions'
import { Route as LegalLoanTermsRouteImport } from './routes/legal.loan-terms'
import { Route as LegalFinancialPrivacyRouteImport } from './routes/legal.financial-privacy'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalAmlKycRouteImport } from './routes/legal.aml-kyc'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminVerifyRouteImport } from './routes/admin.verify'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminChatRouteImport } from './routes/admin.chat'
import { Route as AdminChatIndexRouteImport } from './routes/admin.chat.index'
import { Route as AdminApplicationsIndexRouteImport } from './routes/admin.applications.index'
import { Route as SecureApplicationTokenRouteImport } from './routes/secure.application.$token'
import { Route as AdminChatConversationIdRouteImport } from './routes/admin.chat.$conversationId'
import { Route as AdminApplicationsApplicationIdRouteImport } from './routes/admin.applications.$applicationId'

const StaffInviteRoute = StaffInviteRouteImport.update({
  id: '/staff-invite',
  path: '/staff-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRepaymentRoute = LegalRepaymentRouteImport.update({
  id: '/legal/repayment',
  path: '/legal/repayment',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalMentionsRoute = LegalMentionsRouteImport.update({
  id: '/legal/mentions',
  path: '/legal/mentions',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalLoanTermsRoute = LegalLoanTermsRouteImport.update({
  id: '/legal/loan-terms',
  path: '/legal/loan-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalFinancialPrivacyRoute = LegalFinancialPrivacyRouteImport.update({
  id: '/legal/financial-privacy',
  path: '/legal/financial-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAmlKycRoute = LegalAmlKycRouteImport.update({
  id: '/legal/aml-kyc',
  path: '/legal/aml-kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AdminVerifyRoute = AdminVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatIndexRoute = AdminChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminChatRoute,
} as any)
const AdminApplicationsIndexRoute = AdminApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => AdminRoute,
} as any)
const SecureApplicationTokenRoute = SecureApplicationTokenRouteImport.update({
  id: '/secure/application/$token',
  path: '/secure/application/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChatConversationIdRoute = AdminChatConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => AdminChatRoute,
} as any)
const AdminApplicationsApplicationIdRoute =
  AdminApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulation': typeof SimulationRoute
  '/solutions': typeof SolutionsRoute
  '/staff-invite': typeof StaffInviteRoute
  '/admin/chat': typeof AdminChatRouteWithChildren
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/legal/aml-kyc': typeof LegalAmlKycRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/financial-privacy': typeof LegalFinancialPrivacyRoute
  '/legal/loan-terms': typeof LegalLoanTermsRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/repayment': typeof LegalRepaymentRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/applications/$applicationId': typeof AdminApplicationsApplicationIdRoute
  '/admin/chat/$conversationId': typeof AdminChatConversationIdRoute
  '/secure/application/$token': typeof SecureApplicationTokenRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/chat/': typeof AdminChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulation': typeof SimulationRoute
  '/solutions': typeof SolutionsRoute
  '/staff-invite': typeof StaffInviteRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/legal/aml-kyc': typeof LegalAmlKycRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/financial-privacy': typeof LegalFinancialPrivacyRoute
  '/legal/loan-terms': typeof LegalLoanTermsRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/repayment': typeof LegalRepaymentRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/applications/$applicationId': typeof AdminApplicationsApplicationIdRoute
  '/admin/chat/$conversationId': typeof AdminChatConversationIdRoute
  '/secure/application/$token': typeof SecureApplicationTokenRoute
  '/admin/applications': typeof AdminApplicationsIndexRoute
  '/admin/chat': typeof AdminChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulation': typeof SimulationRoute
  '/solutions': typeof SolutionsRoute
  '/staff-invite': typeof StaffInviteRoute
  '/admin/chat': typeof AdminChatRouteWithChildren
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/legal/aml-kyc': typeof LegalAmlKycRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/financial-privacy': typeof LegalFinancialPrivacyRoute
  '/legal/loan-terms': typeof LegalLoanTermsRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/repayment': typeof LegalRepaymentRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/applications/$applicationId': typeof AdminApplicationsApplicationIdRoute
  '/admin/chat/$conversationId': typeof AdminChatConversationIdRoute
  '/secure/application/$token': typeof SecureApplicationTokenRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/chat/': typeof AdminChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/simulation'
    | '/solutions'
    | '/staff-invite'
    | '/admin/chat'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/verify'
    | '/auth/callback'
    | '/legal/aml-kyc'
    | '/legal/cookies'
    | '/legal/financial-privacy'
    | '/legal/loan-terms'
    | '/legal/mentions'
    | '/legal/privacy'
    | '/legal/repayment'
    | '/legal/terms'
    | '/admin/'
    | '/admin/applications/$applicationId'
    | '/admin/chat/$conversationId'
    | '/secure/application/$token'
    | '/admin/applications/'
    | '/admin/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/simulation'
    | '/solutions'
    | '/staff-invite'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/verify'
    | '/auth/callback'
    | '/legal/aml-kyc'
    | '/legal/cookies'
    | '/legal/financial-privacy'
    | '/legal/loan-terms'
    | '/legal/mentions'
    | '/legal/privacy'
    | '/legal/repayment'
    | '/legal/terms'
    | '/admin'
    | '/admin/applications/$applicationId'
    | '/admin/chat/$conversationId'
    | '/secure/application/$token'
    | '/admin/applications'
    | '/admin/chat'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/simulation'
    | '/solutions'
    | '/staff-invite'
    | '/admin/chat'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/verify'
    | '/auth/callback'
    | '/legal/aml-kyc'
    | '/legal/cookies'
    | '/legal/financial-privacy'
    | '/legal/loan-terms'
    | '/legal/mentions'
    | '/legal/privacy'
    | '/legal/repayment'
    | '/legal/terms'
    | '/admin/'
    | '/admin/applications/$applicationId'
    | '/admin/chat/$conversationId'
    | '/secure/application/$token'
    | '/admin/applications/'
    | '/admin/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SimulationRoute: typeof SimulationRoute
  SolutionsRoute: typeof SolutionsRoute
  StaffInviteRoute: typeof StaffInviteRoute
  LegalAmlKycRoute: typeof LegalAmlKycRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalFinancialPrivacyRoute: typeof LegalFinancialPrivacyRoute
  LegalLoanTermsRoute: typeof LegalLoanTermsRoute
  LegalMentionsRoute: typeof LegalMentionsRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRepaymentRoute: typeof LegalRepaymentRoute
  LegalTermsRoute: typeof LegalTermsRoute
  SecureApplicationTokenRoute: typeof SecureApplicationTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff-invite': {
      id: '/staff-invite'
      path: '/staff-invite'
      fullPath: '/staff-invite'
      preLoaderRoute: typeof StaffInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/repayment': {
      id: '/legal/repayment'
      path: '/legal/repayment'
      fullPath: '/legal/repayment'
      preLoaderRoute: typeof LegalRepaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/mentions': {
      id: '/legal/mentions'
      path: '/legal/mentions'
      fullPath: '/legal/mentions'
      preLoaderRoute: typeof LegalMentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/loan-terms': {
      id: '/legal/loan-terms'
      path: '/legal/loan-terms'
      fullPath: '/legal/loan-terms'
      preLoaderRoute: typeof LegalLoanTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/financial-privacy': {
      id: '/legal/financial-privacy'
      path: '/legal/financial-privacy'
      fullPath: '/legal/financial-privacy'
      preLoaderRoute: typeof LegalFinancialPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/aml-kyc': {
      id: '/legal/aml-kyc'
      path: '/legal/aml-kyc'
      fullPath: '/legal/aml-kyc'
      preLoaderRoute: typeof LegalAmlKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/verify': {
      id: '/admin/verify'
      path: '/verify'
      fullPath: '/admin/verify'
      preLoaderRoute: typeof AdminVerifyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat/': {
      id: '/admin/chat/'
      path: '/'
      fullPath: '/admin/chat/'
      preLoaderRoute: typeof AdminChatIndexRouteImport
      parentRoute: typeof AdminChatRoute
    }
    '/admin/applications/': {
      id: '/admin/applications/'
      path: '/applications'
      fullPath: '/admin/applications/'
      preLoaderRoute: typeof AdminApplicationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/secure/application/$token': {
      id: '/secure/application/$token'
      path: '/secure/application/$token'
      fullPath: '/secure/application/$token'
      preLoaderRoute: typeof SecureApplicationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chat/$conversationId': {
      id: '/admin/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/admin/chat/$conversationId'
      preLoaderRoute: typeof AdminChatConversationIdRouteImport
      parentRoute: typeof AdminChatRoute
    }
    '/admin/applications/$applicationId': {
      id: '/admin/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/admin/applications/$applicationId'
      preLoaderRoute: typeof AdminApplicationsApplicationIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminChatRouteChildren {
  AdminChatConversationIdRoute: typeof AdminChatConversationIdRoute
  AdminChatIndexRoute: typeof AdminChatIndexRoute
}

const AdminChatRouteChildren: AdminChatRouteChildren = {
  AdminChatConversationIdRoute: AdminChatConversationIdRoute,
  AdminChatIndexRoute: AdminChatIndexRoute,
}

const AdminChatRouteWithChildren = AdminChatRoute._addFileChildren(
  AdminChatRouteChildren,
)

interface AdminRouteChildren {
  AdminChatRoute: typeof AdminChatRouteWithChildren
  AdminLogsRoute: typeof AdminLogsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminVerifyRoute: typeof AdminVerifyRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminApplicationsApplicationIdRoute: typeof AdminApplicationsApplicationIdRoute
  AdminApplicationsIndexRoute: typeof AdminApplicationsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChatRoute: AdminChatRouteWithChildren,
  AdminLogsRoute: AdminLogsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminVerifyRoute: AdminVerifyRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminApplicationsApplicationIdRoute: AdminApplicationsApplicationIdRoute,
  AdminApplicationsIndexRoute: AdminApplicationsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplyRoute: ApplyRoute,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SimulationRoute: SimulationRoute,
  SolutionsRoute: SolutionsRoute,
  StaffInviteRoute: StaffInviteRoute,
  LegalAmlKycRoute: LegalAmlKycRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalFinancialPrivacyRoute: LegalFinancialPrivacyRoute,
  LegalLoanTermsRoute: LegalLoanTermsRoute,
  LegalMentionsRoute: LegalMentionsRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRepaymentRoute: LegalRepaymentRoute,
  LegalTermsRoute: LegalTermsRoute,
  SecureApplicationTokenRoute: SecureApplicationTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
